### ISSUE TITLE
Just need a little help

### ISSUE THREAD

**Issue by Chibi1234** [demilich1/metastone#10]

**Comment by Chibi1234** [comment]
Ehmagers sometimes accidentally pressing Go when finishing writing the tile and finishing the thing then looking for solution and presses Close Issue can be a poo poo thing. Well at least I can still reopen and comment on it. I'm looking for a way to add a fusion card which destroys let's say an angry chicken and a mech minion and it summons the mighty Mech Chicken but my brain cells are a little dead :P so I'm looking here for a solution. 

It would also be nice to have a way of seeing which card attacks which in game. When playing against the AI I often can't see what they're really doing. A simple arrow going between the 2 minions attacking or a history bar where I can see their actions.

**Comment by webadict** [comment]
Hey Chibi,
Are you looking for SPECIFIC cards to be fused, or are you looking for only a certain number of general types? Or both?

Like, I can try to help if you give me a better idea of a specific scenario. Does it have to be Angry Chicken and a Mech minion on your side of the field when you play the Spell card Fusion to summon MechaChicken? Does that only work in that exact scenario? Also, what do you have so far?

**Comment by Chibi1234** [comment]
Scenario:

My board has an Angry Chicken and a random mech, lets say its an Annoy-O-Tron for this example. Then i play a spell card that destroys all Angry Chickens on the field togheter with all mechs, and for each Angry Chicken destroyed a Mech Angry Chicken is summoned. There could be lets say 1 mech and 5 angry chickens but it would still summon 5 mech angry chickens.

Also im not sure if metastone is built in such a way to make this possible but it would be awesome to play some sort of fusion card like that!

**Comment by webadict** [comment]
It's well within the ability of the program, but it might involve a bit of
work. The only missing part is probably Mecha Chicken. Sounds similar to a
combination of spells: Ysera Awakens (allows specific cards to be a
condition for the spell, which you can use for Angry Chicken instead),
Poison Seeds (destroys all minion and summons a minion in its place), and
Mimiron's Head (destroys all the Mechs). You'll essentially check to see if
any Mechs are on board, and if so, destroy them all and replace all Angry
Chickens with Mecha Chickens.

Does that help point the way? I'd like to see how far you can get with some
code and help fix any issues you have on the way.

**Comment by Chibi1234** [comment]
{
	"targetSelection": "NONE",
	"id": "spell_angry_mechanization",
	"spell": {
		"class": "MetaSpell",
		"spell1": {
			"class": "InstantDestroySpell",
			"condition": {
				"class": "CardPropertyCondition",
				"cardId": "minion_angry_chicken"
			},
		},
		"spell2": {
			"class": "SummonSpell",
			"card": "token_sheep",
			"targetPlayer": "OWNER"
		},
		"class": "DestroySpell",
				"target": "FRIENDLY_MINIONS",
				"filter": {
					"class": "RaceFilter",
					"race": "MECH"
	},
	"name": "Angry Mechanization",
	"description": "BLABLABLA FARTS N STUFF",
	"type": "SPELL",
	"heroClass": "DRUID",
	"rarity": "EPIC",
	"baseManaCost": 0,
	"collectible": true,
	"set": "CUSTOM",
	"fileFormatVersion": 1
}

Well i made that but ehm when i try to start the game it says ''Error Invoking Method''

Did i do something wrong?

**Comment by Chibi1234** [comment]
https://mega.nz/#!7B9nFAyC!L3LqpnJfvlkFbCev2HEVKeLioisvnaN8wp8khVZ7jUs

**Comment by webadict** [comment]
Hey Chibi,

One mistake I see off the bat is that you have two classes in your spell
object. This will cause errors as you can't have two of the same key in a
json object. What you could do is embed your Meta Spell inside another Meta
Spell so that you can have the destruction of mechs happen before the Angry
Chicken change, so you don't accidentally kill your newly summoned mechs.
Or just put the part after spell2 inside its own spell3 (and the move it to
happen first.)

I'm not at a computer so it's harder to help, but hopefully that helps.
