### ISSUE TITLE
[Flamestrike] + [Imp Gang Boss]

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#101]
When you fill up the enemy board with 7 Imp Gang Bosses and then Flamestrike it, you will be left with 7 1/1 in MetaStone whereas in Hearthstone you would face an empty board.

The problem lies within this method in GameLogic:

```
public boolean canSummonMoreMinions(Player player) {
		int minionsInPlay = 0;
		for (Minion minion : player.getMinions()) {
			if (minion.isDestroyed()) {
				continue;
			}
			minionsInPlay++;
		}
		return minionsInPlay < MAX_MINIONS;
	}
```

which explicitly does not count dead minions towards the minion cap. Changing that method to 

```
public boolean canSummonMoreMinions(Player player) {
		return player.getMinions().size() < MAX_MINIONS;
	}
```

does fix that problem, but I am afraid that may have other unintended consequences.
@webadict Could you think of any scenario where that might be an issue? Otherwise I would go ahead and make that change.

**Comment by mayuso** [comment]
What would happen if you do the same with, let´s say for example, Harverst Golem instead of Imp gang boss?

In HearthStone, you would get 7x 2/1, right? Would this work like this in MetaStone too after the change you are proposing?

**Comment by demilich1** [comment]
Just tested this, yes, this still work correctly after the change

**Comment by mayuso** [comment]
I can think of some other cases, but most of them are Deathrattles, so I assume that if this works for Harvest Golem, it should work on the rest of deathrattles too. I think it is ok to patch the bug this way. (I don´t even know how you guys find this rare case bugs haha).

(Side note: I was thinking about Sylvanas in a full board scenario, but it is the same case as Harvest Golem, I think).

**Comment by webadict** [comment]
Grim Patron? If you have a full board and some die to damage and some
don't, it might summon more Grim Patrons that it shouldn't.

**Comment by webadict** [comment]
No, if anything, this should fix it, right? I say do a test case with the
2/6 that summons 2/2s. Have it summoned first and then fill the board. Kill
everything at the same time. If they all summon, then I wrote death
resolution correctly and deathrattles won't matter. If both the Grim Patron
and this case succeed, then everything should work, right?

**Comment by demilich1** [comment]
Okay, good test cases. I will add those as unit tests and if they all succeed, I will commit this change.

**Comment by demilich1** [comment]
Grim Patrons work as expected, however the Wobbling Runts test fails. So here is how the test is scripted:

1. First player: end turn
2. Second player: Summon Wobbling Runts
3. Second player: Summon 6 Wisps -> board is full
4. Second player: end turn
5. First player: Summon Malygos
6. First player: Play empowered Flamestrike for 9 damage
7. Result: One token remains on the board

Because the Wobbling Runts was summoned first, he also first resolves his death effects. Since there are still 6 Wisps on the board, there is only one slot left for the first token, while the others will fail to summon. Now my question is: Is this behaviour correct? I actually expected all three tokens to appear

**Comment by webadict** [comment]
No, it should summon 3 Runts, since all minions are removed from the board before they are summoned (Or at least, they should be.) I'm gonna guess that this was intended for deathrattles when initially made, and I probably planned it around that as well...

Hmm, tough call. We SHOULD remove all the minions from the board and save their positions when removed. I think I can fix this, which actually fixes another bug at the same time that no one probably noticed anyhow.

**Comment by demilich1** [comment]
I am still commiting my changes now, as this bug is not related to the .canSummonMoreMinions() method.

**Comment by webadict** [comment]
Alright, I can tell you what to fix then. Give me a second while I write it out.

**Comment by webadict** [comment]
It's adding a Map to checkForDeadEntities() in GameLogic, storing the minion and the position it died in.
Then remove the dead minions.
Then process the deathrattles.
You'll probably have to remove the minion removal in the destroy() functions.

This should fix it.

**Comment by demilich1** [comment]
Okay, will try that out (still splitting it up in two commits)

**Comment by webadict** [comment]
If this is fixed, you'll know by having a Haunted Creeper and Harvest Golem on the field in that order summoned in that order. Kill both at the same time, and you should have Haunted Creeper summon both of its minions at position 0 and 1, and Harvest Golem summons its minion at position 1, so that the Spectral Spiders are wrapped around the remaining mech.

**Comment by demilich1** [comment]
It works! Thanks for the hints, also the test cases you are providing are very helpful.
