### ISSUE TITLE
Stat swapping

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#104]
Here is another bug report I received via email. 

*If you play a card such as Power Word: Shield on a minion, and then switch that minion's attack and health via another card, its maximum health will not be updated correctly. Metastone will update that minion's maximum health by simply adding the amount of health that was added by the first card (in this case +2 from Power Word: Shield) to the new health value that resulted from the switch. This results in that minion being labeled as damaged, allowing for heals and activating cards such as Execute and Rampage. If you switch the attack and health of a minion with no prior modifiers, Metastone seems to handle maximum health correctly.*

The issue with wrong health scores pops up quite frequently (also in regards to silence), so I think we should add some units tests to cover those scenarios.

**Comment by webadict** [comment]
Fixed the bug that caused this. Also fixed a related enrage bug as well.

I cannot find any instances of silences being incorrect (After this fix.)

Test cases:
Test Case 1
Warbot + Inner Rage. (4/2)
Crazed Alchemist Warbot. (2/4)
Inner Rage Warbot. (5/3)

Test Case 2
Flametongue + Warbot (3/3)
Brann Bronzebeard
Crazed Alchemist Warbot (5/5)

Test Case 3
Flametongue + Warbot (3/3)
Crazed Alchemist Warbot, but drop in between Warbot and Flametongue (3/1)

**Comment by webadict** [comment]
NOTE: Test Case 3 might fail. I don't know.
