### ISSUE TITLE
[Bug] Lord Jaraxxus incorrect interactions

### ISSUE THREAD

**Issue by webadict** [demilich1/metastone#12]
-Lord Jaraxxus activates Snipe, but has 15/15 HP after Hero replacement.
-Lord Jaraxxus activates Repentance, but has 15/15 HP after Hero replacement.
-Lord Jaraxxus activates Mirror Entity, but destroys the copied minion after summon.

**Comment by demilich1** [comment]
Has been fixed with https://github.com/demilich1/metastone/commit/eb4928fb350589f25878377268618a42c6608225
