### ISSUE TITLE
Swipe Spell doesn't deal damages correctly 

### ISSUE THREAD

**Issue by gr3x** [demilich1/metastone#129]
Hello,
first: big thanks for all your work. Metastone is amazing :-)

This issue just to report that when we use Swipe Spell, 4 damages are given to ALL enemies instead of just one and 1 damage to all other ones.

best regards,

**Comment by kairos4242** [comment]
Hmm, doesn't seem like this'll be too hard to fix, I'll take a look when I get home. Thanks for the help!

**Comment by webadict** [comment]
Found it. It was my bad when I updated all the values of spells to function as ValueProviders as well. It'll be fixed.

**Comment by gr3x** [comment]
thanks guys 👍

**Comment by webadict** [comment]
Nah man, thanks for bugtesting and posting!
