### ISSUE TITLE
Wrong card name for Twin Emperor Vek'lor

### ISSUE THREAD

**Issue by gr3x** [demilich1/metastone#135]
When we import a deck from hearthpwn which contains this card we got an error:
15:09:51 ERROR - Card with name Twin Emperor Vek'lor could not be found

fix: rename inside the json file linked to this card the name like that:
	"name": "Twin Emperor Veklor",
--->
	"name": "Twin Emperor Vek'lor",

I don't think there is any impact by making this change.

best regards,

**Comment by demilich1** [comment]
This is fixed with #134
