### ISSUE TITLE
[Shifter Zerus] Target not found

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#139]
There is an exception when simulating a large number of games which involves Shifter Zerus. I don't know the exact circumstances, will investigate more later.

**Comment by webadict** [comment]
I think I figured it out:

When Shifter Zerus turns into another Shifter Zerus, it adds a second trigger to the card to transform it. When the card transform, it leaves the hand, which causes the trigger to freak out and try to transform a card that's in the graveyard, which it seems to have problems finding. I think this shouldn't be too hard to fix, so I'll try.

It's no wonder I couldn't reproduce it often enough to figure it out.
