### ISSUE TITLE
Cannot delete new decks

### ISSUE THREAD

**Issue by webadict** [demilich1/metastone#141]
Only decks that come with the installation are able to be deleted. Any decks created after installation cannot be deleted.

**Comment by akoscz** [comment]
Aye..  my bad, this is my doing.  I'll look into it after work tomorrow.

**Comment by akoscz** [comment]
I've got a fix ready to address the deletion issue. https://github.com/demilich1/metastone/compare/master...akoscz:user_decks
Before I open a PR I want to figure out how to get rid of all the merge commits from the history.

Also, I think the the proper fix that's needed is to differentiate the built-in decks from user decks in the UI.  For instance, built-in decks cannot be deleted because they are shipped with the app in the cards.jar file so we should not give the user the option to delete it from the UI.

**Comment by webadict** [comment]
Reset the index to demilich's master branch. I'm only used to doing this on Eclipse, so I have no idea how to do it for you, but that will remove the merge commits, but leave the working branch intact.

I'm not as much of a fan of being unable to delete the built-in decks, mostly because this feels disingenuous to the simulator. This is mostly because I would want to be able to drop the built-in ones (They're not the greatest. I literally just try to add what I think is either fun or best represents a class.) Being stuck with them seems a bit lame, especially when I'm probably going to add something stupid like Yogg Reno Duplicate Mage or Choose Both Aggro Druid. Plus, it removes the ability to modify the deck to your liking, leaving the extra copy behind.

**Comment by demilich1** [comment]
How about this:
When MetaStone starts we copy all the premade decks in cards.jar to the users home folder. At the same time we create a file which contains the information "last time decks copied was with version 1.0.2". Now whenever MetaStone is started again, it first checks this file and if the program version is not newer than the "last copied with version" entry, it does nothing. The user may delete or change decks at will.

Whenever we release a new version, we will copy all internal decks again. There are two edge cases here: What about decks modified by the user and what about deleted ones? For now, we could opt to ignore both cases, as this is the same behaviour as before. When all decks were .json files in the /decks folder, we would override them all with each new version anyway. Later on we could add a "version" field to the deck file itself, which is written whenever a deck is modified. Then only premade decks with a version higher than the users deck file would overwrite existing ones.

**Comment by akoscz** [comment]
I just finished coding up a very similar approach :)   I simply write out a properties file with a `decks.copied` field to indicate if we need to copy decks.   Did not take into account the scenario of copying the decks again for a new release.  I was thinking more along the lines of leaving that in the user's control.  For instance, if a user chooses to modify one or more of the decks for whatever reason and then we copy our bundled decks after an app upgrade we essentially will wipe out the changes the user has made.  If the user wants to get all the decks again from our bundled set in cards.jar, they would simply delete the `metastone.properties` file and launch the app.

You will see something like this in the logs on app startup informing the user that cards have been copied:
```
00:43:38 INFO  - Copying Decks from file:/Users/akoscz/workspace/metastone/cards/build/libs/cards-1.1.0.jar to /Users/akoscz/metastone/decks
00:43:38 INFO  - cards-1.1.0.jar!/decks/zoolock.json  -->  /Users/akoscz/metastone/decks/zoolock.json
00:43:38 INFO  - cards-1.1.0.jar!/decks/yoggsaron_tempo_mage.json  -->  /Users/akoscz/metastone/decks/yoggsaron_tempo_mage.json
00:43:38 INFO  - cards-1.1.0.jar!/decks/reno_cthun_mage.json  -->  /Users/akoscz/metastone/decks/reno_cthun_mage.json
00:43:38 INFO  - cards-1.1.0.jar!/decks/old_gods_patron.json  -->  /Users/akoscz/metastone/decks/old_gods_patron.json
00:43:38 INFO  - cards-1.1.0.jar!/decks/nzoth_rogue.json  -->  /Users/akoscz/metastone/decks/nzoth_rogue.json
00:43:38 INFO  - cards-1.1.0.jar!/decks/midrange_darwin_shaman.json  -->  /Users/akoscz/metastone/decks/midrange_darwin_shaman.json
00:43:38 INFO  - cards-1.1.0.jar!/decks/divine_aggrodin.json  -->  /Users/akoscz/metastone/decks/divine_aggrodin.json
00:43:38 INFO  - cards-1.1.0.jar!/decks/cthun_priest.json  -->  /Users/akoscz/metastone/decks/cthun_priest.json
00:43:38 INFO  - cards-1.1.0.jar!/decks/cthun_druid.json  -->  /Users/akoscz/metastone/decks/cthun_druid.json
00:43:38 INFO  - cards-1.1.0.jar!/decks/beastrattle_hunter.json  -->  /Users/akoscz/metastone/decks/beastrattle_hunter.json
00:43:38 INFO  - cards-1.1.0.jar!/decks/astral_communion_druid.json  -->  /Users/akoscz/metastone/decks/astral_communion_druid.json
```
I agree a better solution would be to version the decks.  I say we open up an improvement ticket and put it in the backlog for now.

**Comment by demilich1** [comment]
I like this solution. What about you @webadict ?

**Comment by webadict** [comment]
I like it too.

**Comment by akoscz** [comment]
Was there any other code changes we were going to make for this bug fix?    Just asking cuz I see that we merged the PR but have not close the bug.

**Comment by webadict** [comment]
Tested. Seems to work. I'll close it next time I can.
