### ISSUE TITLE
[Starfall] Fandral Staghelm version

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#150]
The Fandral Staghelm version of Starfall is incorrectly dealing 2 damage to the enemy hero.

I looked at it and saw it was using the 'Swipe' spell, which won't work as Swipe also hits the hero. Now I considered changing it to a MetaSpell with two spells - however this would mean that Spell Damage would be applied twice. Anyone knows how this works on Hearthstone?

**Comment by webadict** [comment]
The Hearthstone version is a Swipe without the Hero damage (I believe, as
it could be main target, then each other target, which kills things like
Imp Gang Boss. I cannot test this just yet.) It should not apply Spell
damage twice on any Fandral version (literally, each one is a different
spell entirely.)

**Comment by webadict** [comment]
Alright, did some digging. Cannot find any information. Luckily, this can be easily fixed some other time. So, I'm going to assume this is how it works: 7 damage to ANY minion, 2 damage to all other enemy minions, Swipe form. This involves reworking Swipe a bit. I think I can get this working.

**Comment by webadict** [comment]
Don't have the cards to test it, and when I asked some experts, I got some half-hearted answers. I'll eventually get Fandral and I can test it then.
