### ISSUE TITLE
Problem compiling app on Windows 7

### ISSUE THREAD

**Issue by BBXAXX** [demilich1/metastone#153]
Hello, I have following problem compiling MetaStrone, I've been trying to figure out this compile problem for about 3 hours but couldn't find any solution. 

So, when I type in CMD: **gradlew.bat run** it starts compiling but then ends with error: 

> What went wrong:
> A problem occurred evaluating script.
> Could not find JavaFX Packager Tools, please set one of [jfxrtDir in Gradle Properties, JFXRT_HOME in System Environment, JAVA_HOME in System Environment, java.home in 
> JVM properties]

I installed latest JDK **jdk1.8.0_91** also my **jre1.8.0_91** is in **C:\Program Files\Java** directory.

I've been trying to add **JAVA_HOME**, **JFXRT_HOME** in
System->Advanced->Environment variables but it didn't worked.

I'd like to hear some info regarding how to solve or how to set this variables so Metastone will compile.

Is it possible in any way, that somebody could upload compiled program **ready to run** to avoid this errors?

Thanks in advance for anyone who are willing to help me with this.

**Comment by webadict** [comment]
I believe you need "gradlew.bat app:run" to run it.

**Comment by BBXAXX** [comment]
Same issue after "gradlew.bat app:run".

**Comment by demilich1** [comment]
JAVA_HOME needs to point to the specific JDK folder, so it should be something like
`JAVA_HOME = C:\Program Files\Java\jdk1.8.0_91`
Also, if you add something to the environment variables, you need to close and re-open all command prompts before the variable will take effect.

If all fails you can always to the [Releases](https://github.com/demilich1/metastone/releases) section and download the latest 1.1.0 installer (which is a ready-to-run version)

**Comment by BBXAXX** [comment]
Oh thank you very much for that installer :) I had specific folder in environment variables, but I was in the same command prompt all the time. Re-opening command prompt helped, thanks :)

**Comment by BBXAXX** [comment]
Is MetaStone working only in 64-bit Windows? I installed it throught installer and it says that MetaStone isn't compatibile with my system, I have 32-bit Windows 7.

**Comment by demilich1** [comment]
Unfortunately yes, the installer version is only compatible with 64 bit 
systems. However, you can always download the metastone-1.1.0_jar.zip 
release, unzip it and then run app-1.1.0\bin\app.bat (this version 
should be compatible with all operating systems). Please note that you 
may get a warning prompt from Windows claiming the app.bat may harm your 
computer (it won't) ;)

**Comment by akoscz** [comment]
So this is interesting,  I opened up my Android UI project that I haven't touched for a week or two and while rebuilding the module I ran into this exact same issue!   Strangely enough, I only encounter this problem when building from within IntelliJ/AndroidStudio.
``` 
Gradle tasks [clean, :android:generateDebugSources, :android:compileDebugSources]
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred evaluating script.
> Could not find JavaFX Packager Tools, please set one of [jfxrtDir in Gradle Properties, JFXRT_HOME in System Environment, JAVA_HOME in System Environment, java.home in JVM properties]
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 0.62 secs
FAILURE: Build failed with an exception.

* Where:
Script '/Users/akoscz/workspace/metastone2/app/javafx.plugin' line: 60

* What went wrong:
A problem occurred evaluating script.
> Could not find JavaFX Packager Tools, please set one of [jfxrtDir in Gradle Properties, JFXRT_HOME in System Environment, JAVA_HOME in System Environment, java.home in JVM properties]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

I did update to AndroidStudio 2.2 Preview 2 in the last 2 weeks.  The command line builds are working fine for me. So it must be something with the version of the Java SDK that's being used.  Looks like the error is on line 60 of the [javafx.plugin](https://github.com/demilich1/metastone/blob/master/app/javafx.plugin).  An exception is thrown if any of the files on the search path cannot be found.  The JavaFX Packager Tools file that it's looking for is `ant-javafx.jar` and it's expecting to find it any of the following locations: 
```
[
     'jfxrtDir in Gradle Properties': {jfxrtDir},
     'JFXRT_HOME in System Environment': {System.env['JFXRT_HOME']},
     'JAVA_HOME in System Environment': {System.env['JAVA_HOME']},
     'java.home in JVM properties': {System.properties['java.home']}
],
[
     'ant-javafx.jar', 'lib/ant-javafx.jar', '../lib/ant-javafx.jar'
]
```

IntelliJ/AndroidStudio ships with a version of the Java SDK bundled in the IDE distribution.  I verified that there is no `ant-javafx.jar` present in the Java SDK distribution in IntelliJ/AndroidStudio where as the Java SDK installed system wide indeed has the `ant-javafx.jar` file in the `jdk1.8.0_66.jdk/Contents/Home/lib/` folder.

@BBXAXX I would be interested to know if your installation of jdk1.8.0_91 contains the `ant-javafx.jar` file in any of the directories within your JAVA_HOME.

**Comment by webadict** [comment]
I ran into this issue, but I kept tinkering and it started working. No idea
why, just assumed it was on my end

**Comment by BBXAXX** [comment]
@akoscz Yes, **ant-javafx.jar** file is located in **C:\Program Files\Java\jdk1.8.0_91\lib**. Also I set JAVA_HOME with variable value: **C:\Program Files\Java\jdk1.8.0_91** in Environment Variables and it detected this file, and ran successfully without any error.

**Comment by akoscz** [comment]
@BBXAXX glad to hear you got it working!   I was contemplating if we are going to have to start bundling `ant-javafx.jar (1.1Mb)` and `jfxrt.jar (18Mb)` within the project libs dir in case the JRE no longer distributes them, but it sounds like that's not the case.  We'll keep an eye on this to see if this issue crops up again but for now I think we're good.

**Comment by demilich1** [comment]
Closed for now
