### ISSUE TITLE
Importing to Eclipse does not work

### ISSUE THREAD

**Issue by mayuso** [demilich1/metastone#155]
After some time on classes, I am back, I want to import the current code to Eclipse and it simply does not work.

The whole project is marked as an error, every class is in the wrong directory (This makes the package definition fail).

I can run it well from gradle, it's just importing to Eclipse what fails. Any solution to this?

I am on Ubuntu 16.04 LTS using Eclipse 4.6, not sure if that is relevant or not.

**Comment by webadict** [comment]
You have to import the subprojects: game, app, cards, shared. Then you need
to fix the dependancies and turn off the errors that show up with it
(circular dependancy, which is an issue that shouldn't exist.) Basically,
under the Build Path, you might need to import the necessary projects to
each subproject, as well as configure the source folders.

**Comment by mayuso** [comment]
Wow, why make it so hard? Why not make each sub-project a package of the same project? I will try now. Thanks :)

**Comment by webadict** [comment]
The subprojects are packaged in the main project. There's usually an option
to import all subprojects as well. Sometimes it doesn't work.

These are some of the issues with the structure. It'll get fixed
eventually. It just doesn't feel like a problem I know how to fix.

**Comment by akoscz** [comment]
@mayuso  Take a look at the [README.md](https://github.com/demilich1/metastone/blob/master/README.md) file, there's instructions on how to import the project into Eclipse.

- Open Eclipse and choose `File > Import > General > Existing projects into workspace`
- Select the `Search for nested project` checkbox on the Import Projects screen.
- Change `Eclipse > Preferences > Java > Compiler > Compiler Complience Level` to 1.8
- Change `Eclipse > Preferences > Java > Compiler > Building > Circular dependencies from `Error` to `Warning`. There is a known bug with importing multi-module gradle projects into Eclipse. The IDE of choice for working with gradle projects is IntelliJ IDEA.

**Comment by mayuso** [comment]
@akoscz I followed that guide.

All of that works fine, what is not working is the rest, all the classes do not recognize the package they are in, anyway, I will find a way to make this work, thank you for answering.

**Comment by mayuso** [comment]
Same error keeps appearing:

[Import cannot be resolved](http://imgur.com/duTCpBc). That file does not exist.

**Comment by webadict** [comment]
Do you have the Gradle add on installed?

**Comment by mayuso** [comment]
I do.

**Comment by demilich1** [comment]
There are two commands you need to run for the project to work in Eclipse:

`gradlew compileBuildConfig`
`gradlew eclipse`

The error in the image you linked suggests that the build config is not yet created, this should be resolved with the first command.

**Comment by mayuso** [comment]
I am sorry but I give up, this is too hard for me, thanks for trying to help me. I leave you the last error message I found, just in case you want to check it out.

    ./gradlew compileBuildConfig

    FAILURE: Build failed with an exception.

    * What went wrong:
    Task 'compileBuildConfig' not found in root project 'metastone'.

    * Try:
    Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with  --info   or    --debug     option to get more log output.

    BUILD FAILED

    Total time: 3.613 secs

**Comment by mayuso** [comment]
Making a Java 8 clean install on Ubuntu 16.04 LTS fixed this issue.

I can't really explain what the problem was, because I don't know, but it is fixed now. Sorry for being so annoying, but I could not give up, I HAD to make this work :)

**Comment by demilich1** [comment]
Kudos for not giving up ;)
