### ISSUE TITLE
Remove cards from within JAR

### ISSUE THREAD

**Issue by webadict** [demilich1/metastone#158]
Can we get the cards accessible from outside the JAR file again? I think their inclusion into the JAR is more of a detriment to the people that would like to use the program. I understand why it's built like this, but it only makes finding card issues that much harder to find, plus it removes the ability to add custom cards, which is one of the bigger reasons I started working on this project to begin with.

Overall, I am against this particular change, and would like it changed back. Without this ability, I feel like we lose a huge chunk of our userbase, and my ability to bring users to our program diminishes.

**Comment by webadict** [comment]
Ha, this IS in the program... It's just got an error in the functionality (You have to put the cards into a metastonecards folder...), plus it removes most people's ability to make new cards (Since they don't have access to the old cards.) However, I still want the card resources available outside the JAR.

**Comment by akoscz** [comment]
Sorry, I don't follow what you mean.  Users can add custom cards into their `metastone/cards` dir.  There's a section on that in the (README.md)[https://github.com/demilich1/metastone/blob/master/README.md]. 

So for decks, we copy them into the `metastone/decks` dir.  We can do the same for cards.  Users will then be able to edit the cards to their hearts content.  If cards get messed up and users want to start fresh, they will simply have to just delete the `metastone/cards` folder and on next app startup we will copy all the cards again.

**Comment by webadict** [comment]
This still makes the cards an unchangeable part of the simulator, unless
it's recompiled. And without the ability to see other cards locally, you
are very unlikely to see custom cards (how could anyone make a card using a
format they don't know?) If you want to make a spell that deals 4 damage,
wouldn't looking Fireball make a lot of sense? But you can't.

It's basically hardcoded into the game, which is not cool.

Also, the current implementation is missing a file seperator, so it doesn't
have the right folder for custom cards.

**Comment by akoscz** [comment]
Maybe I wasn't making my point clearly enough.  Once we copy the cards into the `metastone/cards` dir, this location will be the source of truth for the cards.  All cards will be available for users to see and edit.  The `cards.jar` file that is distributed within the app will simply be treated a backup source to allow users to start fresh if necessary.

**Comment by webadict** [comment]
That's sounds a lot better, thanks!

How exactly would resetting the `cards` dir work, though?

**Comment by akoscz** [comment]
I added a couple of bullet points in the [README.md](https://github.com/demilich1/metastone/pull/166/commits/1e62b5cbd7272635b4d6110127c8f456e0851cbb) about it.

- In the rare chance that your card files get messed up beyond repair,  you can always force the app to overwrite your local card files with the versions distributed with the app in `cards.jar`.
   * _Option 1_: Delete the `~/metastone` dir.  
      * You **WILL LOOSE** all your changes, including **ALL new files** you may have added. DANGEROUS! MAKE A BACKUP!!
      * Linux/Mac OSX `rm -rf ~/metastone`
      * Windows `rmdir /s C:\Users\[username]\Documents\metastone`
      * Card data files will be copied in their prestine state after you restart the app.
   * _Option 2_: Edit the `~/metastone/metastone.properties` file and update the `cards.copied` property.
      * change `cards.copied=true` to `cards.copied=false`
      * New files you may have added will NOT be affected.
      * All card files that are distributed with the app will be overritten after you restart the app.

**Comment by webadict** [comment]
Nice. I approve.

**Comment by webadict** [comment]
Fixed via #166
