### ISSUE TITLE
No Visuals but Running (Surface Book/Windows 10)

### ISSUE THREAD

**Issue by thodl15** [demilich1/metastone#159]
Hey all,

I've been looking into using Metastone for simulation purposes, and I seem to have hit a snag when trying to run it on my laptop. As it says in the subject, I'm attempting to run it on a Microsoft Surface Book running Windows 10. I've attempted to install it via both the .exe file, and compiling it myself, and the issue appears to exists in both methods. When I try to run it, the program window opens up, but there are no apparent graphical cues on the screen. However, when I try to look at the preview located on the taskbar, the graphics show in the preview. Using that, I could see that the program is running properly, and it looks to be solely a visual bug.

My initial hypothesis for the visual bug would be the native screen resolution for the Surface Book, which is 3000x2000, causing some sort of problem with the resizing. Now, understandably this is a relatively minor issue, but I am just curious if someone might have some knowledge as to what might be going on behind the scenes.

If there is any other information needed, I can try to supply it if possible.

**Comment by webadict** [comment]
Are you using the current release or a different version?

**Comment by thodl15** [comment]
I tried with both the latest version (1.0.2), and an earlier release (0.9.9). Both resulted in the visual bug.

**Comment by mayuso** [comment]
Those versions did not have any window resizing IIRC.

Can you check your Java version? I have seen people with problems with JavaFX on old version of java.

**Comment by thodl15** [comment]
Yep:

Version 8 Update 91

**Comment by webadict** [comment]
@thodl15: Would you mind attaching some screenshots of what happens?

I think you might be right about your screen resolution, though. Just a feeling, really, but I suppose I'm less knowledgeable on the graphical side of this than many of the other contributors.

**Comment by thodl15** [comment]
Sure, I can absolutely do so. I'll add them to the next post I put up.

**Comment by webadict** [comment]
Hmm, I'm doing some testing, and I'm not seeing the issue occur with different resolutions, so maybe I'm wrong about that. I'd still like to see exactly what's happening when this occurs.

**Comment by thodl15** [comment]
Okay, so I have three screenshots showing the effect. One of them had to be taken with my phone in order to actually capture what was going on, strange enough.

![compiled visual issue](https://cloud.githubusercontent.com/assets/17462014/15836958/37500b86-2c05-11e6-8f33-eb1c07a1752e.PNG)
So this first one is showing that it is occurring after compiling the application directly. The interesting thing that happened while I was trying to take this image, is that the moment I hit the screenshot button, the proper graphics flicker onto the screen. Now, it does not get captured by the screenshot itself, but it distinctly appears long enough for my eyes to acknowledge it.

![github master visual issue](https://cloud.githubusercontent.com/assets/17462014/15836956/37211d30-2c05-11e6-8313-d2b96dba4ccc.png)
This is a verification that the issue also happens when trying to compile using the current branch of the GitHub repository. I followed the same steps as the previous, but alas it too resulted in this screen.

![preview graphic](https://cloud.githubusercontent.com/assets/17462014/15836957/3721890a-2c05-11e6-98fb-688a04f24e24.JPG)
This image is showing that the graphic is properly rendered by the preview function for the Windows. Apologies once again for the phone-quality resolution on this one.

I wish there was a way to help further replicate this problem, but I can't think of any other factors that might be causing it. The only other thing that I could imagine would be the fact that I am using Windows 10, but I do not believe that it would cause something like this. I do not have another Win10 machine I can test with, so the jury's out for that hypothesis.

I'll try to keep tabs on this chain, but I probably won't be able doing too much more responding until tomorrow morning, so about fourteen hours.

**Comment by webadict** [comment]
Quick question: Can you click one of the buttons? Perhaps, if you would, could you try to enter either Play Mode or Sandbox Mode?

**Comment by webadict** [comment]
Also, I'm pretty sure it's not a Windows 10 issue, as I've been running it on both 7 and 10 without any issues so far.

**Comment by thodl15** [comment]
Aha! When I actually get into a game, the mulligan screen has shown up. But when I clicked the button, the screen went back to blank. So that is progress, from my perspective!

**Comment by thodl15** [comment]
By wildly clicking on the right side, I managed to make a Mana Wraith appear for a split second.

**Comment by webadict** [comment]
Interesting. It seems that portions of the GUI do show up... There might be an issue rendering one of the JavaFX portions for your computer. Maybe re-installing Java might fix it? Sounds like one of the more important and common pieces too (Especially since you're getting the mulligan and Cards to show up, which are fairly basic.

Try to see if you can hover over one of your cards. It should pop up a bigger version of a card (Like the Mana Wraith.)

**Comment by demilich1** [comment]
Both the mulligan screen and "briefly show the card that was just played" are implemented as popups. 

The bug is quite strange and I suspect it is a bug in JavaFX. But maybe there is a work-around?

First of all: Is there any error in the log file, i.e. the installed version of MetaStone writes the log to <installation path>/app/report.log. Any errors or exceptions in there?

I also found the following forum thread where a user has the exact same problem: https://community.oracle.com/thread/3752935?start=0&tstart=0
In the last post he claims that inserting one call to .setOpacity(0.0) before showing the stage and one call of .setOpacity(1.0) after showing the stage fixed the problem for him. Maybe you could try adding this to the code and compiling it locally? If it works, we can add that for all users

**Comment by thodl15** [comment]
After installing & running the v1.0.2 version of Metastone, I ran through the steps to get into Play Mode once again, able to see the mulligan screen, and continued for a little bit with my random guessing through the side menu. I just looked at the log file, and there did not seem to be anything relevant to the issue: There were two lines, one indicating the first time the ./training folder was made, and the second line indicating an failure to connect to the update server. I tried to attach the log file "as is," but I had to convert it to a text file so GitHub would allow me to upload it.

[report.txt](https://github.com/demilich1/metastone/files/302580/report.txt)

As for the Oracle community post, I just read through it, and it looks promising. I will see if I can implement it locally, and will report back with the results of the test.

**Comment by thodl15** [comment]
And success!

 It was just a simple fix exactly like the one suggested in the forum post. From what I can tell, it seems to be working properly in the Play Mode environment, but I can look into other potential sections of the program as well.

I'm proposing the change to the "MetaStone.java" file now.

**Comment by thodl15** [comment]
So, for a full summary:

\(Tested in v1.1.0\)

The change works when the program is compiled while the computer is in its "Tablet Mode," as opposed to the regular display style for most laptops. 

That is, when the program is set to start up in a full-screen mode, the graphics will display properly in all checked cases. Furthermore, when switching the Surface Book back to "Laptop Mode," Metastone still runs properly. 

However, if the program is compiled in Laptop Mode, the visual bug is still present. I'm not entirely certain as to why, however this is at least a step in the right direction.

**Comment by demilich1** [comment]
Fixed by #160
