### ISSUE TITLE
[Cone of Cold] + [Imp Gang Boss]

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#161]
Bug report received via email:

_If I Cone of Cold an Imp Gang Boss that's inbetween two minions, the Cone of Cold will hit the Imp that's summoned from the Imp Gang Boss instead of the minion that was originally to the right of it. I'm guessing the Cone of Cold is hitting the three minions one at a time from left to right instead of doing so at the same time, thus allowing on-hit triggers to occur after each hit._

Note: This is the behaviour in real Hearthstone; in MetaStone you always freeze the two minions next to the targeted one even if a token is spawned. In my opinion is more intuitive but sadly wrong :(

I added a unit test for this case, which fails at the moment

**Comment by webadict** [comment]
This is an issue with Adjacent Effect Spell. It just need to grab the adjacent minions first, then perform the spells. Easy enough fix.

**Comment by demilich1** [comment]
But this is how it works right now, when you got the following board:

`Chillwind Yeti | Imp Gang Boss | Chillwind Yeti` 

the correct behaviour would be that both Yetis and the Imp Gang Boss are damaged, but the Freeze effect should apply to the left Yeti, the Imp Gang Boss and the spawned token. With the current code, the damage and the freeze effect always hit the same minions

**Comment by webadict** [comment]
Ah. Got it. Then it's half the Adjacent Effect Spell, and half the Cone of Cold. Basically, applying the same fix for this that was did to Blizzard will fix it!

**Comment by webadict** [comment]
Boom, done.
