### ISSUE TITLE
[Spellbender]

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#162]
Spellbender does not work correctly with cards that have a condition attached, i.e. [Execute] or [Shadow Word: Death]. Since the Spellbender does not fulfill that condition, it is unaffected. The correct behaviour would be that the Spellbender is destroyed in both cases.

**Comment by webadict** [comment]
Ah, same issue as Djinni. Shouldn't be too difficult to fix this one.

**Comment by webadict** [comment]
I think I've fixed it, assuming that no other cards use the filter for anything other than what it can target.

**Comment by webadict** [comment]
I think I should clarify here: I fixed it in the same way that I forcibly removed the Filter. This is probably incorrect in the grand scheme, but it works as a quick fix for now.

**Comment by webadict** [comment]
Fixed via #163
