### ISSUE TITLE
[The Beast] + [Redemption]

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#169]
Received via email:

_I encountered the following interaction between the Finkle Einhorn summoned from The Beast and Redemption: Player 1 plays The Beast. Player 2 destroys The Beast and receives the 3/3 Finkle Einhorn. Player 1 plays an Ironfur Grizzly along with a Redemption. Player 2 attacks into the Ironfur Grizzly with the Finkle Einhorn resulting in both minions dying. In this case Redemption should trigger and Player 1 should be left with a 3/1 Ironfur Grizzly. Instead, Player 1 is receiving a 3/1 Finkle Einhorn._

**Comment by webadict** [comment]
What the heck? I gotta see this.

**Comment by webadict** [comment]
Hahahah, whoops! Looks like ANY opponent minion that dies is redeemed for the Light!

**Comment by demilich1** [comment]
lol :smile:

**Comment by webadict** [comment]
Alright, fix incoming. Just a simple check to make sure that it's the secret owner's minions...
