### ISSUE TITLE
Weapon Deathrattle Resolution

### ISSUE THREAD

**Issue by kairos4242** [demilich1/metastone#180]
I know we've had some trouble with this in past, but it looks like this still isn't fixed. 
From the advanced rulebook:

> You have a Death's Bite equipped and your enemy has a Haunted Creeper on the board. You play Perdition's Blade comboed targeting the Haunted Creeper. Regardless of order of play, the Battlecry goes off, reducing the Haunted Creeper to 0 Health, then the Deathrattle goes off, reducing the Haunted Creeper to -1 Health, then a Death Phase ensues where the Haunted Creeper is removed from play and its Deathrattle resolved, the Spectral Spiders untouched.[102]

In Metastone, the Death Phase of the Haunted Creeper triggers before the deathrattle of the Death's Bite does, killing both Spectral Spiders.

As well, the rulebook also says:

> You have a Sword of Justice equipped and an Illidan Stormrage on the board, and play a Truesilver Champion. During the On Play Phase, your old weapon is still equipped, and we see the spawned Flame of Azzinoth get buffed and durability deducted before finally it is replaced by the Truesilver Champion.[103]

This test succeeds, however, and the Flame is successfully buffed before the weapon is destroyed.

As well, the rulebook gives some insight into why the first test fails:

> The reason why the Deathrattle of your old Weapon is triggered in the middle of the Phase, rather than during a subsequent Death Phase, is because there is no concept of pending destroy coded for Weapons. For more information, see the Instant Weapon Destruction section.

Do weapons have pending destroy in Metastone, like minions do? If so, then maybe the issue is there.

**Comment by webadict** [comment]
Weird... I always thought the deathrattle went off at the same time... That's actually a fairly easy fix.
