### ISSUE TITLE
[Summoning Stone]

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#185]
Received via email:

_If you control a Summoning Stone and play a spell that's been modified by Preparation, the Summoning Stone should trigger off of the modified cost. Triggering off of the original cost used to be a Hearthstone bug, but was fixed with the Old Gods patch._

I wrote a unit test for that issue, but was unable to find a quick fix. As far as I can tell the issue is that the Preparation ManaModifier is already used up when the SpellCastedEvent is fired, so the call to .getModifiedManaCost returns the value without the Preparation effect.

**Comment by webadict** [comment]
This should probably happen with every mana modifier, right? Because right
now it does not, for sure.

**Comment by webadict** [comment]
I checked, and that's correct. All modifiers to spell cost (Loatheb, Millhouse, Sorcerer's Apprentice, Preparation, Thaurissan, etc.) effect the minion summoned. The same goes for Gazlowe's ability trigger. It is only the actual cost paid, so this might require storing that information when it happens. It could be a Player or game variable named LAST_MANA_COST or whatever. It requires a bit of a rewrite, but that's cool.

**Comment by webadict** [comment]
Boom, solved. Let's call that a wrap for v1.1.0, and work on Buffs next.

**Comment by webadict** [comment]
Actually, I'm gonna fix Gazlowe too, hold up.
