### ISSUE TITLE
Confessor Paletress/Golden Monkey summon non legendary minions

### ISSUE THREAD

**Issue by Lykrast** [demilich1/metastone#187]
Basically, whenever I used one of these cards through playing or in sandbox mode, I always get totally random minions, instead of legendary minions only.

Happens in version 1.10, I have not modified the files for both of those cards and it happens even in sets without any custom cards.

**Comment by webadict** [comment]
Looks like someone (me) forgot to put in a negation. Issue fixed in next version.
