### ISSUE TITLE
Incorrect attributes for some cards

### ISSUE THREAD

**Issue by Lykrast** [demilich1/metastone#192]
Version 1.1.0 on the website, I just noticed over time that some cards have some wrong attributes in their files. I might be wrong in one or two because I fixed them myself on my computer some days ago and might have forgotten the exact thing that was fixed, but I know I had to fix those cards :

- Eater of Secrets gets buffed with the user's Secrets (should be opponent's)

- Cyclopian Horror only gets buffed by minions with Deathrattle (should be all enemy minions)

- Faceless Shambler doesn't have Taunt, even in its description (it has Taunt in Hearthstone)

- Twilight Elder is an epic (should be a common)

- Princess Huhuran has no tribe (should be a beast)

- Mana Tide Totem has no tribe (should be a totem)

**Comment by Lykrast** [comment]
Another one I just noticed today is that Ogre Ninja doesn't have Stealth (it should).

**Comment by webadict** [comment]
Haha, nice, alright, I'll get these working soon.

**Comment by webadict** [comment]
Alright, will be fixed in next update!

**Comment by webadict** [comment]
Hey, just an fyi, there's no need to close this before it gets added to the project. You know, just in case my programming is so terrible that there's no way we can use it.

**Comment by Lykrast** [comment]
Sorry about that, I don't use github that much.

Also, Hearthstone got a new patch and Silithid Swarmer is now a Beast, so I thought it was appropriate to tell it here in case you missed it.

**Comment by demilich1** [comment]
Thanks @webadict 

I also added the BEAST tag to Silithid Swarmer
