### ISSUE TITLE
[Release] 1.1.1

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#195]
1.1.1 has been released containing a bunch of bug fixes. Head over to the [Release section](https://github.com/demilich1/metastone/releases) to see the full change notes and/or download the binaries.

**Comment by webadict** [comment]
As far as I'm aware, Summoning Stone should not summon minions next to it.
It's actually one of the rare ones that doesn't, though this may have been
changed recently.

**Comment by demilich1** [comment]
Oh okay, I will double-check that in-game and if it doesn't remove it for the next release.

**Comment by webadict** [comment]
All Karazhan cards should be available for use and testing!

**Comment by webadict** [comment]
Alright. Seems like all the cards SHOULD be 100% correct. This seems like a good time to release a new version.
