### ISSUE TITLE
Corrupted Seer only targets enemy minions

### ISSUE THREAD

**Issue by Lykrast** [demilich1/metastone#197]
As the title says, Corrupted Seer only targets enemy minions, which is not how it behaves in game or what its text says, as he is meant to damage "all non-Murloc minions".

It also has an incorrect rarity as it is a rare card in Hearthstone and a common one here.

Addendum : I also noticed the scarabs summoned by Obsidian Destroyer are murlocs, while they are beasts in hearthstone.

EDIT : Also, Rend Blackhand is incorrectly labelled as a Dragon (which he is not).

**Comment by Lykrast** [comment]
Other error I've found : Hooded Acolyte is a 2/6 here, should be a 3/6.

**Comment by webadict** [comment]
I'll fix these while adding some new ONiK cards
