### ISSUE TITLE
[Bug] Tracking is not implemented correctly

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#2]
The Hunter card 'Tracking' does not offer the player the choice which card to choose. Instead it pulls 3 random cards out of the card and gives the player a random one. We should change that to the proper implementation.

We may re-use the mulligan method of the AI to prompt for the selection.

**Comment by webadict** [comment]
With the advent of the Discover mechanic coming in the League of Explorers expansion, I think implementing this with the mechanic is probably the best way to go. I'm planning to implement the mechanic by creating 3 choices, similar to how Battlecry activates, with no possibility to backtrack. I don't know how this will affect AI, but that can wait until after the mechanic is implemented.

So far, something around 30% of LoE cards have been added, but I'll be adding more until they're set to go.

**Comment by webadict** [comment]
Next Pull Request should fix this issue!

**Comment by demilich1** [comment]
Fixed
