### ISSUE TITLE
Unable to select a Warlock deck! (version 1.1.1)

### ISSUE THREAD

**Issue by Grymmjow** [demilich1/metastone#202]
Whenever I select the Warlock class, the deck list that appears is actually the warrior one, making it impossible to pick a warlock deck.

**Comment by mayuso** [comment]
In what game mode does this happen? All of them? I will try to reproduce it and fix it.

**Comment by webadict** [comment]
I think I saw this issue once. It's got something to do with the drop down
list bugging out on the deck selection screen. I couldn't figure out what
caused it, but it's pretty rare and hard to reproduce. Plus, what it
effects changes each time too.

**Comment by mayuso** [comment]
I don't think I am going to be able to fix this issue, I have it identified, and I know how to fix it, but I can't build the project on my Ubuntu machine (Same problem I described on #155 , for some reason this problem is back and I can't make it work). Sorry.

**Comment by webadict** [comment]
Do you have a branch I can test? I'll upload it for you if need someone to test it.

**Comment by greatwanz** [comment]
Just found this project yesterday, looks fantastic.

I hunted around for much longer than necessary for what's causing this issue, and turns out it is caused by "minion_alexstrasza"' being misspelled as "minion_alexstraza" in the Maly Dragonlock deck.

**Comment by webadict** [comment]
...Lol
