### ISSUE TITLE
The Boogeymonster triggers when not attacking

### ISSUE THREAD

**Issue by Lykrast** [demilich1/metastone#207]
It isn't something I noticed immediatly (mostly because it's very rare to see him), but here's the thing : 

The Boogeymonster's effect is supposed to only triggers if he attacks into a minion and kills it, currently in Metastone the effect triggers when the boogey kills a minion regardless of he is the one that attacked or not. That means that attacking the boogeymonster itself and dying from the attack will still buff him, which it should not.

I believe this might also apply to Giant Sandworm, but since its effect is not noticeable when it's not your turn, the bug doesn't visibly do anything for that card.

**Comment by webadict** [comment]
Good catch! Fixed it up right this time!

**Comment by webadict** [comment]
Hmm.. I guess I technically fixed it for 99% of issues. There's one left, where if the enemy has a Misdirection, and you attack into it, and it redirects to your own Boogeymonster which kills your minion, then the Boogeymonster will be buffed. But, that's a little bit harder to nail down.

**Comment by webadict** [comment]
Fixed with latest PR.

**Comment by webadict** [comment]
Actually... Let's leave it open, since it's only ALMOST fixed.
