### ISSUE TITLE
[Bug] GUI in Collection Screen not showing cards correctly.

### ISSUE THREAD

**Issue by Stick1314** [demilich1/metastone#225]
![](https://i.gyazo.com/d02b528322ae43be984c63b3c40c16a9.png)
Not sure what could be causing it. Don't get any errors upon startup, nor is there anything in the report.log. I made a custom card which could be causing it, I'll move it elsewhere and see if the issue is fixed, and if so I'll paste the card's code. If it is the card, I'm not entirely sure why it would cause this specific issue.

**Comment by Stick1314** [comment]
Yep, it's the card. It REALLY doesn't like it for some reason. I put it back in, though I forgot to close the game and it immediately went unresponsive and wouldn't even close. Had to kill it through Task Manager.

The card is my attempt to basically make something similar to the spell in the Prologue of ONIK that reduces the spells in your hand to (0), except it spans across all cards, reduces them by 3 instead of making them free, and it's a permanent thing rather than until the end of the turn.

Formatting is fine, and looked into Preparation and Thaurissan to make the card. Maybe it should be a minion with an Aura? Like I said before, I'm not sure why the card is causing this issue.

{
	"id": "spell_crop_circle",
	"Name": "Crop Circle",
	"baseManaCost": 2,
	"type": "SPELL",
	"heroClass": "Any",
	"rarity": "COMMON",
	"description": "Reduce the cost of cards in your hand by (3).",
	"targetSelection": "NONE",
	"spell": {
		"class": "CardCostModifierSpell",
		"target": "FRIENDLY_HERO",
		"cardCostModifier": {
			"class": "CardCostModifier",
			"target": "FRIENDLY_HAND",
			"operation": "SUBTRACT",
			"value": 3
		}
	},
	"collectible": true,
	"set": "CUSTOM",
	"fileFormatVersion": 1
}

**Comment by webadict** [comment]
CardCostModifiers don't go on Spells, I don't think. You should use Thaurissan as your copy for what spell to use.

**Comment by webadict** [comment]
Oh wait, I just can't read it that well. Idk, let me think about it.

**Comment by webadict** [comment]
Name is capitalized.

**Comment by Stick1314** [comment]
Ah, works now, thanks.
