### ISSUE TITLE
Can see enemy secrets even when cards are hidden

### ISSUE THREAD

**Issue by Lykrast** [demilich1/metastone#231]
Hovering over an enemy secret shows the secret itself even when the opponent's cards are hidden. This is minor as you can simply choose to not hover over them but it still seems unintended.

On another related note, it could be useful to have the secret display on screen when triggered, like how Yogg-Saron does now.

**Comment by webadict** [comment]
Was this done in Sandbox Mode or Play Mode?

**Comment by webadict** [comment]
It seems to be both. Well, alright then. I'll see what I can do.
