### ISSUE TITLE
Several Bugs

### ISSUE THREAD

**Issue by DominusMaximus** [demilich1/metastone#237]
Hello. Here are some issues I've encountered recently:

- The mana cost penalty from Freezing Trap isn't being overwritten by Aviana or Naga Sea Witch. For example, if an Aviana is played while a minion affected by Freezing Trap is in hand, the cost of that minion should be set to 1 (Metastone currently sets it to 3) . If a minion is returned to hand by a Freezing Trap while an Aviana is already on board, Metastone will correctly set that minion's cost to 3.

- According to https://hearthstone.gamepedia.com/Steward_of_Darkshire, when it comes to Steward of Darkshire interacting with Sword of Justice, a 1 health minion should receive divine shield if it's played, but not if it's solely summoned. For example, playing a Bilefin Hunter should result in a 3/2 Bilefin _with_ divine shield, but a 2/2 Ooze _without_ it. Murloc Tidehunter is similar: the result should be a 3/2 Tidehunter with divine shield, and a 2/2 Scout without it. The Paladin hero power should result in 2/2 minions without divine shield. Likewise, Stand Against Darkness should result in 5 2/2s without divine shield. Currently, in each case listed above, Metastone will grant the divine shield. 

- Nightbane Templar should be set to summon a Whelp on each side of the Templar, similar to Onyxia.

- Netherspite Historian's battlecry isn't triggering because of an unnecessary line in the json:

"targetSelection": "ENEMY_MINIONS"

**Comment by webadict** [comment]
Thanks for the bug report! I can fix 3 and 4 right away. I can probably fix 1 in a little bit of time... But 2 looks to be a really tough one to fix, for a lot of reasons. I didn't realize that Steward of Darkness applies differently for played and summoned, which is a real pain in the butt, honestly. My guess is that one probably won't be fixed any time soon.

**Comment by DominusMaximus** [comment]
Yeah, I understand what you're saying. Off the top of my head, I can't think of another case that would be affected by this timing interaction. The whole "summon resolution step" and all its details is still mysterious to me.

**Comment by webadict** [comment]
Right. This might be fixable with a few additional events programmed in, but it's really silly that it even causes this. It's likely a bug, but probably one that won't be acknowledged or fixed until 3 months from now, and then it will be secretly patched randomly.

**Comment by demilich1** [comment]
I agree, this sounds like an inconsistency in the Hearthstone code. While I usually think we should mimic all interactions as accurate as possible, in this case we would need a major refactoring just to introduce a bug. This feels so wrong ;)

**Comment by webadict** [comment]
Alright, fixed 1, 3 and 4. Did an update to ReturnMinionToHandSpell that allows the use of spells within it, so that the minion returning to hand can have a spell cast on it.
