### ISSUE TITLE
Error trying to compile on Windows

### ISSUE THREAD

**Issue by kairos4242** [demilich1/metastone#238]
![2016-08-31 13_57_23-posh git metastone master](https://cloud.githubusercontent.com/assets/17713263/18144242/ec74b4ce-6f82-11e6-986e-dd0d75371f82.jpg)

I reinstalled the JDK twice, and set the JAVA_HOME system variable, restarting the console each time. No luck.

**Comment by demilich1** [comment]
Could you please try to type 
`echo %JAVA_HOME%`
and post the output here?

**Comment by kairos4242** [comment]
in cmd.exe it returns c:\Program Files\Java\jdk1.8.0_102\bin\javapackager.exe

In the git shell, however, it just returns %JAVA_HOME%

**Comment by webadict** [comment]
I believe that should go to the bin folder, not the packager executable. Is
that correct @demilich1?

**Comment by demilich1** [comment]
Actually it should just point to the root directory of the Java installation, definitely not the javapackager.exe. So in your case `c:\Program Files\Java\jdk1.8.0_102\` should be correct

**Comment by kairos4242** [comment]
Works perfect now, thank you!
