### ISSUE TITLE
2 Bugs (Barnes, Priest of the Feast)

### ISSUE THREAD

**Issue by DominusMaximus** [demilich1/metastone#249]
- Priest of the Feast isn't triggering when a spell is cast.

- Despite the correct board position tag in the json, Barnes will summon its battlecry minion on the far right of the board.

**Comment by webadict** [comment]
Wrong keyword in Priest of the Feast, and a rewrite of the Spell that Barnes casts should fix that one.

**Comment by demilich1** [comment]
The Priest of the Feast is fixed now, rewriting Barnes is probably going to take a bit longer, so that one is still open

**Comment by webadict** [comment]
Don't worry, bro, I got you. I'm just fixing a few other spell bugs at the
same time. I'll have something up soon.

**Comment by webadict** [comment]
Boom, fixed.
