### ISSUE TITLE
Fix this please :3

### ISSUE THREAD

**Issue by Chibi1234** [demilich1/metastone#25]
Me: Starts a match playing against Warlock.
*5 minutes later*
Me: Bwuahhaha! Die bot! I have made a board far superiour to yours! Deathwing, Ysera and NEFARIAN! *Ends turn*
Bot: Plays corruption
Me: Wait who did he use corruption on?!?!?!?
Bot: *Ends turn*
Me: Hmmmmm im 1 turn of lethal... just need to set it up one more damage next turn >:P... *Uses Inner fire on ysera*
Me: *Ends turn*
*Ysera dies*
Bot: Says to me through telekenetic powers ''BwahahahHA! Metastone does not show which card was corrupted so u didn't know which card i casted it on! It was your Ysera! hahahahahhahah!
Me: *RAGE QUIT*

**Comment by webadict** [comment]
I think the better solution to this would be a history log, but that isn't likely to be implemented for... a while. I can see this being addressed in maybe 3 or 4 releases, depending on how things are going.

**Comment by Chibi1234** [comment]
oh Okie :3

**Comment by demilich1** [comment]
Pretty much what webdict said. While I want to provide some graphical feedback for basic effects like Frozen, Divine Shield, etc Corruption is an one-of-a-kind outlier and unlikely to get its own visual. I agree that a history log would be very useful.
