### ISSUE TITLE
A few minor bugs

### ISSUE THREAD

**Issue by Lykrast** [demilich1/metastone#254]
- N'Zoth's First Mate is missing the Pirate tag

- Hovering over weapons or hero powers in play doesn't show their full card text like it does on minions or cards in hand

- _(Related suggestion rather than bug)_ Visual mana cost of hero powers is static, would be great to have it visually change with modifiers such as Saboteur or Maiden of the Lake

**Comment by webadict** [comment]
Might as well get this one out of the way while @demilich1 is here ;)
