### ISSUE TITLE
Attack buffs

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#259]
One of the recent changes apparently introduced a bug regarding buffing the attack stat.

Two of our unit tests are failing right now: 
`CardInteractionTests.testAttackBuffStacking`
and
`SpecialCardTests.testSpitefulSmith`

Unfortunately I won't be able to investigate this until next week; if it is not fixed by then, I will take a look

**Comment by webadict** [comment]
I bet it was the change to Charge, but I'll look.

**Comment by webadict** [comment]
Charge affects the first test that fails, since it doesn't increase Attack by 2 anymore. The second test might fail because of Aura changes? I'm not sure.

**Comment by webadict** [comment]
Uh... whoops. Fixed THAT bug. _Someone_ forgot to apply triggers to Auras.

**Comment by webadict** [comment]
Alright, now it's good.

**Comment by demilich1** [comment]
Cool, thanks!
