### ISSUE TITLE
UI improvement possibly?

### ISSUE THREAD

**Issue by Chibi1234** [demilich1/metastone#26]
''UI improvements in general are welcome''

Does anyone know how to acces/change the graphical files? Personally i dont find Metastone's graphics so ''appealing'' to the eye and if you look at Minecraft's UI it has a pretty simplistic one with square buttons. Right now Metastone is covered in plain beige squares, and my point is:

Wouldn't it be better to use a more traditional color like say... Blue. Blue is also less known for being a colour that makes you think alot more (Its true, blue triggers your brain to think and Red triggers the aggresive side of your brain) about your actions. Maybe not a deep blue but maybe a very light blue color. I think that would make it alot more appealling and im willing to make it all myself if needed :D 

And also ''Please do not request better graphical effects'' This is not a graphical effect.

**Comment by mayuso** [comment]
I know how to create JavaFX and Swing interfaces, i could edit this if we think its necessary, but i don´t wanna get lots of work done and then get my pull request denied, so i need confirmation first.

**Comment by webadict** [comment]
If it looks better than the current implementation, I'm almost positive demilich would accept it. And if he doesn't accept it, and it definitely looks better, then I'll keep pull it into mine for sure.

**Comment by demilich1** [comment]
I agree that the MetaStone UI is really bad at the moment. Actually, it was created by me playing around with some random CSS styles and thinking "This is just for testing, gonna make it pretty later on". Now guess what, it stayed this way ;)

All of the UI description files are included in the repository. The layout of the different UI elements is defined in .fxml files (located in src/main/resources/fxml). I am considering moving away from .fxml files in the future though, as they are just so slow. When you click a button in the main menu, it takes several seconds to get to the next screen. There is no large data loading happening, it is just the .fxml parsing.

How an element like a button or a panel looks like is defined in .css files (located in src/main/resources/css). Feel free to tinker with the visuals; while I cannot *guarantee* that I will accept your PR, I will happily do it if the UI looks tidier/more professional.

**Comment by Chibi1234** [comment]
''src/main/resources/css'' I CANT FIND IT! AWIGHVHKVIAW *PANICS AND DIES*

**Comment by demilich1** [comment]
https://github.com/demilich1/metastone/tree/master/src/main/resources/css

**Comment by Chibi1234** [comment]
Thx!
