### ISSUE TITLE
Mean Streets of Gadgetzhan 

### ISSUE THREAD

**Issue by webadict** [demilich1/metastone#266]
Well, looks like another update. Luckily, I managed to get all the cards added, and functional (Except for Kazakus... But I have NO idea how that's going to work here. Sometimes, I think they add some cards to make this project harder...)

So, I've got to add the following:
- Updated Deck Formats :white_check_mark:
- Updated Decks ✅ 
- All Mean Streets of Gadgetzan cards. (132 Finished/132 Revealed/132 Total)
- Tri-Class Cards :white_check_mark: Done, as well as multi-classing!
  - These cards currently function as Neutral cards, but are only obtainable with that current Hero Class. Hopefully this is correctly implemented.
- Kazakus ... :white_check_mark: is my greatest creation! MUAHAHAHAHAHAHAHA!
- Fixing some bugs. This includes:
  - Did you know that Deck Triggers didn't actually get added to minions when they're added after the fact, nor removed when taken out of the deck? :white_check_mark:  Well, it does both now!
  - Did you know that the Card Filter for multiple Hero Classes did the opposite of what it should've? :white_check_mark: Well, it works now!
  - Did you know that InDeckFilter doesn't take into account multiple copies in a deck? ✅ Well, they do now!
  - Did you know that cards pulled from the deck and summoned from cards like Deathlord were lost track of for milliseconds and gave MetaStone a panic attack? :white_check_mark: Well, it's on medication for that now!
  - Did you know that some cards had different internal ids than their file names? :white_check_mark: Well, not anymore!
  - Did you know that conditions had no idea who sourced them, meaning you could never have the source figure out anything about itself? :white_check_mark: Well, they've all been made self-aware now!
  - Did you know that secrets would occasionally think they're being modified while displaying, due to Mad Scientist? :white_check_mark: Well, he's been taken care of now!
  - Did you know that the query for cards is always based on the DeckFormat, which means that cards from other formats (Let's say Webspinners summoned from Ball of Spiders) could never be grabbed with Mindgames? ✅ Well, every card can be found now!

Along with these changes, I'm going to try to implement the following:
- REMOVAL OF CARD IDs. :white_check_mark: This is currently DONE. Cards now receive a CardID based on their filename.
- JSON Auto-Formatting. This way, cards will be automatically formatted upon being accepted by the game, and then rewritten to be extra pretty. Because pretty is always the answer.
- A few method renamings that are relics of a lost age.
- Activate Battlecry Spell, allowing the spell to activate the battlecry of a minion again. May or may not work.
- ... Buff Update. Maybe. I have a working version of this, but it has severe limitations with the system. But it is FANTASTIC when I can push several buffs onto minions without having to go crazy with it (Like having a changing buff, and then doubling it.) I have no clue when this will actually be fully added, but it'd be cool to have.
- Other things. If you've got a specific type of change or spell you'd like to see in MetaStone, reply now and I'll add it to this list.
- Updating various Spell create() methods to actually... you know... CREATE the spells. :white_check_mark: DONE!

**Comment by DominusMaximus** [comment]
Good stuff, looking forward to those new cards. Kazakus seems tricky. This link has useful notes on it: http://hearthstone.gamepedia.com/Kazakus

I'm guessing a straightforward way would be to create a card for each of the 135 combinations, similar to how you've handled Fandral by creating a card for each of his "choose one" combinations. I don't program much so I don't know how you would handle the bit that says "...the game automatically presents certain effects in the order that is best for the player...", or how you would combine the 3 successive discover effects into choosing one of the 135 cards.

On a different note, a reminder on the recent changes to Murlocs: http://www.hearthpwn.com/news/1812-hearthstone-patch-15181-murloc-card-changes-bug

**Comment by webadict** [comment]
As far as I can tell, each of the 135 combinations is actually programmed into the game, but that's just a guess. It IS possible to make a spell that actually creates cards with custom effects. In fact, that would probably be easier (Kinda. It would certainly create better customization, overall.) They likely just had the effects placed in order of priority (Transform > Damage > Summon > Heal, for example), so making it work with a custom spell class is completely doable. Now... extending that to hit more is the tricky part, but I might be able to do it. Who knows?

Also, I already got the Murloc update.

**Comment by webadict** [comment]
I might actually need to do a custom spell for that, since there are rumors that the other tri-class legendaries are going to be "Discover a custom weapon" and "Discover a custom minion", which might all be doable, cool enough. The only issue is that these cards could have unfortunate issues with cards that copy based on their names... Hmmm...

**Comment by DominusMaximus** [comment]
What do you mean by cards that copy based on their names? Also, in your prior comment, what did you mean by "extending that to hit more"?

**Comment by webadict** [comment]
Eh, maybe I'm just paranoid. Sometimes I get mixed up with what spells do what, so it might not be an issue.

The extending to hit more is that I have a vision for this spell, and I can extend that vision to make it better. At first, I assumed "Maybe this is 135 spells", but then I thought that might be fairly complex for this... So, instead, I came up with something else:
- The mana cost is the tough part. That part essentially enables the last two portions, and makes them uniquely different. So, how I implement that is the most important part.
- The two-part discover portion is relatively easy. Simply give it a list of 10 "spell parts", and then have them choose a certain number of them (In this case, 2.) These parts would be listed in order of operation, so if you want "transform" to always happen first, it should be listed first, and so on.
- These spell parts can be added to a customly built card, but... If you copied the card, would it still function as it should?

**Comment by DominusMaximus** [comment]
A custom spell sounds very nice. The "choose one" template seems like a good starting point. For example, if you have Kazakus in hand, you will see 3 different cards you can play (similar to Keeper of the Grove, which shows up as 2 cards): 

Summon: Kazakus (Create a 1-Cost spell)
Summon: Kazakus (Create a 5-Cost spell)
Summon: Kazakus (Create a 10-Cost spell)

Those 3 would be listed within the Kazakus json as "options", with each pointing to a unique discover spell (similar to Raven Idol, but that will also utilize your custom spell code). 

About that order of operation, from this post by Mike Donais it doesn't seem like there will be an order to which they are presented (I understand why you would want to do so): https://np.reddit.com/r/hearthstone/comments/5b5mlg/the_mean_prerelease_reveal_chart_all_currently/d9mnjzu/

From his description it seems like the order of the two effects are fixed afterwards. The reason I bring this up is that, depending on how many effects need to be ordered in the first place, wouldn't ordering their appearance affect their odds? For example, if only 2 of the 10 effects happen to be sensitive to ordering, and neither of them come up randomly within the first discovery, would you eliminate their chance to appear in the second discovery depending on what was first chosen?

**Comment by webadict** [comment]
Hmm... no, that would fail double battlecries. It was a good idea though. I
might just add it as part of the custom spell, which is regrettable, but oh
well. I'll see what I can do.

**Comment by webadict** [comment]
Also, I wouldn't order their appearance. Instead, I would order the operation afterward. For example, I present the bot with 6 possible spell effects:
Transform All > Damage All > Heal Hero > Heal All > Damage Enemy Hero > Summon Token
There are 6 possible choices to begin with, but they are currently ordered. So, I could choose the Summon Token and the Damage Enemy Hero effects. It doesn't matter what order I choose them in; it will create the spell with Damage Enemy Hero, then Summon Token. Giving the components in operational order should make this happen fairly effectively.

**Comment by DominusMaximus** [comment]
Ok I see what you're saying. That handles it nicely.

**Comment by webadict** [comment]
I already regret my decision to make this customizable.

**Comment by webadict** [comment]
I no longer regret my decision. Holy crap, it works!

**Comment by DominusMaximus** [comment]
:-) awesome. Sounded like you had hit a major roadblock.

**Comment by webadict** [comment]
Kazakus is now 100% functional. The only pieces I need are his remaining spells. I will also add a way to few the cards that show up. Because I'm awesome.

I only needed to add like 10 more Spell Args, 3 more Parser Args, 2 more Parse Util Types...

**Comment by webadict** [comment]
He's also available to play immediately, if you want to compile commit_stream4.

**Comment by DominusMaximus** [comment]
How do I compile a specific commit stream?

**Comment by webadict** [comment]
https://github.com/webadict/metastone/tree/commit_stream4
This is the most up-to-date branch.

**Comment by DominusMaximus** [comment]
I was able to compile it, but I couldn't find Kazakus within the deck builder, or by searching for it within sandbox mode. I am able to see other Mean Street cards though.

**Comment by webadict** [comment]
Are you building a Mage, Priest, or Warlock deck? Because he is a Tri-class card.

**Comment by DominusMaximus** [comment]
I tried that. I'm also able to see other tri-class cards. In any case, when adding a card to the hand within sandbox mode, all class card should come up within a search, right?

**Comment by DominusMaximus** [comment]
I'm able to see it now. Didn't know the compile would still consider the cards located in My Documents. I copied all of the Mean Street cards to that location and now Kazakus is visible.

It has the same feel as the videos I've seen. 3 discover effects and boom, custom spell. Nice work.

**Comment by webadict** [comment]
The best part is the customizability of the spell. Recreating the spell as a custom him only spell was probably easier, and maybe a bit nicer looking in the end, but the ability to create something similar was too enticing, plus the ability itself is too unique to not make it possible for other cards.

**Comment by DominusMaximus** [comment]
Yeah, the way you wrote out the Kazakus json makes it very easy to customize the different components.

**Comment by webadict** [comment]
The last part is hopefully getting three Discover cards to show up... Then I can remove the Action bar hovers.

**Comment by webadict** [comment]
Status Update:
- Jade Golems are horrible constructs, made entirely of crushed dreams and null pointer errors...
  - Jade Golems have custom card_ids attached to them. This is so that cards can be created and found after creation by other spells ("ReceiveCardSpell" uses the card's id to find it.) This would be GREAT, except that these custom card ids are NOT stored within the CardCatalogue anywhere, so when these are queried... They don't exist. This has been worked around by adding a collection of all temporarily created cards and storing them inside the GameContext. In essence, I have created my own card query within GameContext... Sorry @demilich1, it was a necessary evil. It was either that or I create 30 Jade Golems, and ~135 potion tokens. Not gonna happen.
  - On the plus side, these monsters have created a new way to search through cards: Card Sources! You can choose a Card Source to grab a collection of cards from, and then use it. This removes the previous issue of the InDeckFilter, where it can only filter out cards from the collection; it cannot choose them. This actually helps out in the use of Discovers: There is no longer a need to manually map out how to grab Discover's cards. I can add a Neutral Card Collections and 4 Class Card Collections. This is actually incredibly useful for several reasons: If a card becomes available that doesn't grab cards the same way, then it can be easily modified to work with it. Likewise, this makes some spells superfluous now, as CardSources can replace many of them.
- I have been working on the ability to make, and I'll need you to bear with me on this one, Spell Tribes. This allows ANY card type to have a race (I'm considering renaming it to Tribe, since that's the Hearthstone name), including spells, weapons, and I guess even Hero Powers. The reason for this is that it can make other search categories better, and extends out the use of Card Filters.

And that's all I have for now. I've finally gotten Jade Golems to be findable, but it requires some finicky changes. I'll push a working version of Jade Golem changes (The Spell Tribe stuff is a WIP, so that won't be in any time soon. Plus it's more of a personal improvement, so maybe it will happen...)

**Comment by DominusMaximus** [comment]
I compiled commit_stream2 after commit_stream4 compiled with a bunch of warnings. Should I still report any issues I find while using commit_stream2?

**Comment by webadict** [comment]
It should be the most up to date, so sure!

**Comment by webadict** [comment]
All cards are now added here: https://github.com/webadict/metastone/tree/commit_stream. Still needs bug testing. Will push when ready. Should also contain some bugfixes for things I probably broke.

**Comment by webadict** [comment]
... Whelp, found a bug that I can't get rid of, and I'm not sure how it even works.

Choose One cards do not actually send a TargetAcquisitionEvent... Which is completely and utterly bizarre. But, surprisingly, this means that Spellbender never actually worked with it. Huh. Neither does Mayor Noggenfogger, the dumbest card that's ever existed.

**Comment by webadict** [comment]
Oh man, there are a lot of Choose One bugs...

Bleh.

**Comment by webadict** [comment]
This is so much worse than Kazakus.

**Comment by webadict** [comment]
I might have something working tomorrow. I'll have to rewrite the way Choose One Actions are processed.

**Comment by webadict** [comment]
I'm gonna be honest... I have no idea what I did, but I think it works. Mayor Noggenfogger is a terrible person, and he makes everything worse.

**Comment by DominusMaximus** [comment]
You randomly targeted code with random code to get Mayor Noggenfogger to work.

**Comment by webadict** [comment]
Maybe the game works? Commit Stream is the most up to date. I have a few changes that require card testing before they go live.

**Comment by DominusMaximus** [comment]
I encountered this:

\metastone-commit_stream\game\src\main\java\net\demilich\metastone\game\heroes\powers\HeroPowerChooseOne.java:12: error: HeroPowerChooseOne is not abstract and does not override abstract method hasBothOptions() in IChooseOneCard public class HeroPowerChooseOne extends HeroPower implements IChooseOneCard {

1 error
:game:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':game:compileJava'.

**Comment by webadict** [comment]
Hmm, might've forgot to push that change. I'll recheck.

**Comment by webadict** [comment]
Alright, it's now all in one place.

**Comment by webadict** [comment]
And a few more fixes. Current branch now being pushed for PR.

**Comment by webadict** [comment]
Alright, comprehensive list of all updates since Mean Streets of Gadgetzan was released:

Fixes:
- Fixed several Rarity values being incorrect.
- Fixed most instances of card cost modifiers not properly interacting.
- Fixed Djinni of Zephyrs. Now he truly grants your wish of not being viable.
- Fixed several AI bugs.
- Fixed a bug where Kezan Mystic could give you too many secrets.
- Fixed King's Elekk to not be an actual draw.
- Fixed a bunch of bugs where deck triggers would crash your game.
- Fixed a bug where Auras did not aura correctly.
- Fixed Fel Cannon to stop targeting itself.

Updates:
- Updated error dumps to include comprehensive lists of all actions performed in a game.
- Updated Murloc cards to match changes.
- Updated several conditions to be more versatile.
- Updated summon events to include pre- and post-summon effects.
- Updated decks.
- Updated deck formats.

Additions:
- Added the Mean Streets of Gadgetzan.
- Added the ability to use/make Tri-Class cards.
- Added Card Sources to certain spells, to allow cards to be pulled from certain locations. This means pulling from a deck will increase the chances of cards if they have more in there (Thoughtsteal, Mindgames, etc.)
- Added more customization options for spells.
- Added the ability to give minions multiple triggers.

Removals:
- Removed internal card IDs. Cards now use their file name as a Card ID.

@demilich1: After you update MetaStone to 1.3.0, you can close this issue.

**Comment by demilich1** [comment]
I just published the 1.3.0 release. While there are still some open issues, I consider the version to be stable enough for public use. Thanks to all contributors (@webadict specifically) for this release!
