### ISSUE TITLE
3 Issues

### ISSUE THREAD

**Issue by DominusMaximus** [demilich1/metastone#269]
- When a minion with Ancestral Spirit dies, the resulting minion should be summoned at the same location. Metastone currently summons that minion to the right of all other minions.

- If a player has 7 minions and an Atiesh on board, playing a spell should not remove a durability from Atiesh.

- Lunar Visions is only drawing 1 card.

**Comment by webadict** [comment]
Well, 2 and 3 are easy fixes, and they'll be pushed shortly. 1 is actually a little bit confusing to fix, but that's because of how it's set up. I'll see what I can do.

**Comment by webadict** [comment]
1 is now fixed. Had to add a board position check on the revived minion. This should actually fix a few other cards as well.
