### ISSUE TITLE
I added a wiki page!

### ISSUE THREAD

**Issue by Chibi1234** [demilich1/metastone#27]
I made a small wiki for basic card creation with some extra details that demilich1 has not incluced in his little article in What is metastone?

Some texts i inserted like the wisp didn't show up like it was supposed to. The fireball one is all nice and pretty while the wisp one is a smudder of text! I would appreciate if someone would fix this as my brain is a bit dumb to understand how to make it pretty. Also if anyone finds a grammar problem please change it to the thing it was supposed to be. I write way to fast to worry about grammar ;) GOTTA GO FAST!

**Comment by webadict** [comment]
The issue is the lack of spaces before the brackets. Without those, the text gets pressed together. I'm sure there's a formatting guide somewhere.

**Comment by Chibi1234** [comment]
Wow u really expanded the page ALOT XD

**Comment by Chibi1234** [comment]
Wait were did the page go? It has dissapeared for me!

**Comment by webadict** [comment]
It's still there for me.

**Comment by mayuso** [comment]
Yes, still there, but the design of all repositories has changed (For me), so now you have the link to the wiki above the repository and not in the right part of it.
