### ISSUE TITLE
Spirit Claws wrong mana cost

### ISSUE THREAD

**Issue by SheerSt** [demilich1/metastone#270]
After updating metastone from 1.1.0 to 1.2.0, Spirit Claws still costs 3 mana instead of 1. I see that this issue has been fixed as of Sep 30, but my update was applied after then and this issue appears in the updated version. This is easily fixed in by modifying the card json, but wanted to point out the issue regardless.

Also, Execute costs 1 mana instead of 2 for me, might be related to above issue.

**Comment by webadict** [comment]
It's very likely your cards aren't updating correctly. The easiest way to fix this is to remove your current card repository (Usually in "My Documents/metastone") and then restart metastone.

**Comment by webadict** [comment]
I'm going to close this issue. If you find you're still having problems, please feel free to reopen it.
