### ISSUE TITLE
Mean Street Issues

### ISSUE THREAD

**Issue by DominusMaximus** [demilich1/metastone#271]
- When a Grimestreet Pawnbroker is played a weapon in hand will receive the +1/+1 buff, but when that weapon is played it reverts to its original stats.

- Shaky Zipgunner's buff is only giving +1/+1.

- Counterfeit Coin is labeled as a Priest card. 

- The card name "Illegal Import" should be changed to Smuggler's Run.

- Arghh, I may be old and called Patches, but I still be _charging_ you know!

**Comment by webadict** [comment]
1. Huh... That's dumb. I should maybe fix that.
2. Yeah, saw that one, too. That's fixed.
3. Returned to its rightful owner.
4. Card reveal issue. That's fixed now too.
5. Yarrr, I be forgetful in me old age. He be gettin' his ol' sealegs back fer yer voyage.

**Comment by webadict** [comment]
Weapons now keep their buffs from hand. Also, fixed a bug that caused buffed weapons to not adequately do the things they should.
