### ISSUE TITLE
Latest Update

### ISSUE THREAD

**Issue by DominusMaximus** [demilich1/metastone#273]
- The "ConditionalValueProvider" within Kill Command, Cogmaster, and Cogmaster's Wrench no longer works. I'm guessing there's something up with the interaction between the ConditionalValueProvider and the MinionOnBoardCondition.

**Comment by webadict** [comment]
What! I thought I tested this! Alright, I'll recheck this...

**Comment by webadict** [comment]
Wtf? Okay, maybe I screwed something up there... Not sure what, but I'm checking now...

**Comment by webadict** [comment]
Omg... I'm so stupid.

**Comment by webadict** [comment]
Fixed.

**Comment by DominusMaximus** [comment]
Ok good, now I can go face again.
