### ISSUE TITLE
3 minions from the_old_gods got targetSelection property

### ISSUE THREAD

**Issue by Aurimas86** [demilich1/metastone#277]
MinionCardDesc doesn't have property called targetSelection, however cards from the_old_gods got it in json files:

the_old_gods\mage\minion_servant_of_yogg_saron
the_old_gods\neutral\minion_nzoth_the_corruptor
the_old_gods\neutral\minion_yogg_saron_hopes_end

as "targetSelection": "NONE",

**Comment by webadict** [comment]
Yeah, occasionally, there are a few minor issues like that. On the plus side, this isn't a really big issue, but I can try to address it eventually.
