### ISSUE TITLE
GameContext.clone() doesn't clone SUMMON_REFERENCE_STACK environment value, breaks alphaBeta while evaluating e.g. SwapHpSpell

### ISSUE THREAD

**Issue by doctorpangloss** [demilich1/metastone#282]
The clone code should be updated to handle all the values in the environment that need to be cloned for `alphaBeta` to work correctly. The summon reference stack is the bug I encountered—the stack isn't cloned, so the same reference is getting manipulated by `alphaBeta`.

```
Minion sourceMinion = (Minion) context.resolveSingleTarget(context.getSummonReferenceStack().peek());
```

**Comment by webadict** [comment]
I'm not sure if I understand. It appears it clones perfectly fine for me.

The SummonReferenceStack is an element found in the Environment:
```
public Stack<EntityReference> getSummonReferenceStack() {
	if (!environment.containsKey(Environment.SUMMON_REFERENCE_STACK)) {
		environment.put(Environment.SUMMON_REFERENCE_STACK, new Stack<EntityReference>());
	}
	return (Stack<EntityReference>) environment.get(Environment.SUMMON_REFERENCE_STACK);
}
```
This should be cloned in the clone() method, found on lines 104-106
```
for (Environment key : getEnvironment().keySet()) {
	clone.getEnvironment().put(key, getEnvironment().get(key));
}
```

The only issue I see is that maybe the peek() is empty?

**Comment by webadict** [comment]
If you're using the SwapHpSpell as a Spell, then it would create an issue, since this spell is only used for Battlecry minions. Technically, this is bad practice, so I can fix it anyway, but it makes sense why this card would fail if the ability were used in, say, a trigger effect, since there IS no minion currently being summoned. The spell itself is supposed to switch the HP of the battlecry minion with a target.

**Comment by doctorpangloss** [comment]
I think the issue I'm encountering is that, since `getEnvironment().get(Environment.SUMMON_REFERENCE_STACK)` returns a stack (`Stack<>`) object, cloned `GameContext` 's share the same object for `Environment.SUMMON_REFERENCE_STACK`.

When the AI does `alphaBeta`, it makes many clones and simulates the result of an action. But for all those calls to `alphaBeta`, the same object for `Environment.SUMMON_REFERENCE_STACK` is getting mutated. Subsequent calls to `alphaBeta` essentially are dealing with a corrupted `gameContext` instance even though it was cloned.

I have this issue fixed in my fork. It can be fixed straightforwardly by checking if the environment value for a given key is a stack, and then treating that clone differently. It's going to take me a while to reconcile all my changes, so I thought I would post this here to keep track!

**Comment by webadict** [comment]
That shouldn't matter though, since Entity References point to the same
Entity regardless of how they're cloned. Can you confirm, @demilich1?

**Comment by demilich1** [comment]
EntityReference itself is clone-safe, however the Stack object is not. As @doctorpangloss said, we need to make sure that cloning a GameContext always creates a new Stack instance for each clone. As far as I understand one instance is shared between clones at the moment.

**Comment by webadict** [comment]
Alright, alright, fine. I've created a custom cloning procedure for all the stacks now.
