### ISSUE TITLE
Incorrect 3 cards data

### ISSUE THREAD

**Issue by Aurimas86** [demilich1/metastone#289]
Cards\mean_streets_of_gadgetzan\neutral\minion_leatherclad_hogleader.json
has "heroClass" = "EPIC"

Cards\mean_streets_of_gadgetzan\shaman\spell_finders_keepers.json
has property "attribute" instead of "attributes"

Cards\one_night_in_karazhan\weapon_atiesh.json
has "fireCondition" on TriggerDesc class instead of EventTriggerDesc

**Comment by webadict** [comment]
Sweet. I'll push those out.
