### ISSUE TITLE
[Improvement] Add 'Back to main menu' button during play mode

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#3]
Currently there is no way to prematurely end a game in Play Mode except closing the whole application. We should add a 'Back to main menu' button just like in Sandbox Mode

**Comment by Chibi1234** [comment]
I wish i could code to help with this ; ^  ;

**Comment by webadict** [comment]
Chibi, why do you think you can't help, much less think you can't code?

Like, what makes anyone more qualified to code? I have very little formal experience with coding. I learned everything I learned by simply trying. I'm not a programmer by trade. I started programming for fun in my spare time. That's... pretty much all I've ever done for programming. It just takes practice, just like every other skill. It doesn't matter how old you are. It doesn't matter when you start. You just have to find time to practice. There's a website call codewars.com that has a pretty fun way to learn programming, and the great thing about programming is that you have like all the resources readily available. You just have to start.

**Comment by nalf3in** [comment]
@webadict I looked at codewars and it looks promising ! However, you already need know the basics of Java to get started..  Do you have any ressources to recommend in order to learn those basics ? I already have experienced a bit of python 3 but I was only beginning.

**Comment by kairos4242** [comment]
@nalf3in Have you tried Codecademy? I first learned basic Python there, a while ago. I know they also offer free courses in Java, so if you haven't heard of it, maybe check it out.

**Comment by webadict** [comment]
Yeah, things like codecademy and w3school will give you a good grasp of the
basics. If you ever come across something you don't know, you can always
look it up or even ask. There's tons of resources out there. A lot of
learning will probably come from looking at code and changing parts of it.
