### ISSUE TITLE
Private player constructor has to copy more stuff to support AI

### ISSUE THREAD

**Issue by doctorpangloss** [demilich1/metastone#300]
The player's private copy constructor has to work differently now. I believe there are actions that mutate cards in the `setAsideZone` and `graveyard` now. I was hitting all sorts of CardReference not found exceptions, because instances of Player were sharing the same instance of graveyard / setAsideZone instances. This fixes more crashes in the AI I have been observing.

```java
this.graveyard.addAll(otherPlayer.graveyard);
this.setAsideZone.addAll(otherPlayer.setAsideZone);
```

The code below clones more rigorously.

```java
this.hand = otherPlayer.getHand().clone();
this.minions.addAll(otherPlayer.getMinions().stream().map(Minion::clone).collect(Collectors.toList()));		this.graveyard.addAll(otherPlayer.getGraveyard().stream().map(Entity::clone).collect(Collectors.toList()));
this.setAsideZone.addAll(otherPlayer.getSetAsideZone().stream().map(Entity::clone).collect(Collectors.toList()));
```

**Comment by webadict** [comment]
This is probably correct. I'll fix this eventually.

**Comment by doctorpangloss** [comment]
Also, does `resolveCardReference` need to support `GRAVEYARD` for any reason? Like do the C'Thun effects work when he's in the graveyard right now?

Current code:

```java
			switch (cardReference.getLocation()) {
				case DECK:
					card = findCardinCollection(player.getDeck(), cardReference.getCardId());
					break;
				case HAND:
					card = findCardinCollection(player.getHand(), cardReference.getCardId());
					break;
				case PENDING:
					card = getPendingCard();
					break;
				case HERO_POWER:
					card = player.getHero().getHeroPower();
				default:
					break;
```

**Comment by doctorpangloss** [comment]
Making the clone fix resolves all my other outstanding issues with the decks you've configured! Thanks so much for those hard-won changes.

**Comment by webadict** [comment]
I've modified the code provided to account for hand being a finalized property, in that I've added the cloned collection instead. Should essentially do the same thing.

**Comment by webadict** [comment]
Resolving the Card Reference probably SHOULD, but I don't think any cards are grabbed from the Graveyard ever, except in the case of the Card Condition or the Resurrect spells, which manually check the graveyards, so it shouldn't cause any issues. HOWEVER, it SHOULD check the set aside zones, since cards can be cast from there (Ala Yogg-Saron, or other effects.)

**Comment by webadict** [comment]
The reason why C'Thun isn't an issue, is that the C'Thun buffs modify an internal Attribute of the Player, which is then added to C'Thun when received in hand or when summoned to the field (e.g. Thoughtsteal or Mindgames, respectively.)

You know, in case it matters. Hearthstone isn't really a fan of modifying minions after they're not visible (Graveyard or Deck), but the Set Aside Zone is technically still in play, as minions are moved there a lot and then modified (Something akin to Recombobulater, or possibly Evolution battlecry guy with Brann Bronzebeard.) Lots of fun stuff with the Set Aside Zone that make this a tiny bit difficult.

However, as far as I'm aware, none of these should actually cause issues with card references... But I'll be vigilant, just in case.

**Comment by webadict** [comment]
Also, apparently, we forgot to copy the attributes of players over! That's going too.
