### ISSUE TITLE
Darkshire Councilman counts itself

### ISSUE THREAD

**Issue by Muppet1** [demilich1/metastone#309]
When Darkshire Councilman comes into play it gives itself +1 attack which is incorrect.

**Comment by sohan** [comment]
Hi @Muppet1, for some reason I wasn't able to reproduce this behavior in the code or in Sandbox mode. Can you detail the steps to reproduce this error, and try it again against the latest version of the code base?

**Comment by Muppet1** [comment]
hmm sorry my card list didn't update to the newer version of the card where it works fine.  I manually overwrote the file and all is well.

to keep the app uptodate is there anything I need to do other than just run gradlew.bat I am new to this.

Sorry to have wasted your time looking into this.

**Comment by sohan** [comment]
Cool, glad it works now. And no worries at all -- posting bugs keeps the project robust, and I added a unit test for Darkshire Councilman to make sure the correct behavior never regresses with a future update.

To update the project, you need to sync your local git repository with the server, eg `git pull origin master`. That downloads and merges in the latest code updates to your computer, See https://help.github.com/articles/fetching-a-remote/. After that, run ./gradlew.bat again

**Comment by webadict** [comment]
I'm gonna close this issue. If you notice it again, feel free to open it!
