### ISSUE TITLE
[Bug] Steamwheedle Sniper does not affect hunter hero power's target

### ISSUE THREAD

**Issue by thoughthouse** [demilich1/metastone#31]
When you have a Steamwheedle Sniper on the board, you can target minions, but the damage still goes to face.

**Comment by webadict** [comment]
That's actually the internal SMOrc redirector at work. It automatically
tries to go face if you somehow fail.

But seriously, I'll check it out. It's probably due to how the Hero Power
is coded, overriding the selected target with the internal target.
