### ISSUE TITLE
Missing ids for spells & tokens

### ISSUE THREAD

**Issue by Aurimas86** [demilich1/metastone#311]
These don't contain Id in their json files, but they're referenced from another entities.

secret_potion_of_polymorph
spell_blastcrystal_potion
spell_bloodfury_potion
spell_dragonfire_potion
spell_felfire_potion
spell_freezing_potion
spell_greater_healing_potion
spell_jade_idol
spell_jade_idol_1
spell_jade_idol_2
spell_jade_idol_3
spell_pint-size_potion
spell_potion_of_madness
spell_volcanic_potion
token_crystal
token_kabal_sheep
token_ogre
token_pirahna (actual name is Piranha and weapon name is incorrect)
token_rat
token_tabbycat
token_the_storm_guardian

**Comment by sohan** [comment]
Hi @Aurimas86, from what I can tell, it looks like the `id` field from JSON is never used. Instead, Metastone always generates a card's id from the JSON's filename.

https://github.com/demilich1/metastone/blob/master/game/src/main/java/net/demilich/metastone/game/cards/CardParser.java#L64

It looks like this change was added with MSOG. Maybe the `id` field should be removed from all existing card definitions. @webadict what do you think?

**Comment by webadict** [comment]
Agreed. I just lost my old JSON formating code, so I can't do it all at
once just yet.
