### ISSUE TITLE
Incorrect piranha & piranha weapon titles

### ISSUE THREAD

**Issue by Aurimas86** [demilich1/metastone#319]
Swap letters 'hn'.

https://github.com/demilich1/metastone/blob/a0cc5d924236bbb60c7639501f956e2df814f205/cards/src/main/resources/cards/mean_streets_of_gadgetzan/hunter/weapon_pirahna_launcher.json
https://github.com/demilich1/metastone/blob/8af53dd217fd9a4023182541068db7e503aef11c/cards/src/main/resources/cards/mean_streets_of_gadgetzan/hunter/token_pirahna.json

http://www.hearthpwn.com/cards/49618-piranha-launcher
http://hearthstone.gamepedia.com/Piranha

**Comment by webadict** [comment]
Issue has been merged
