### ISSUE TITLE
Sabertooth Tiger's real name

### ISSUE THREAD

**Issue by Aurimas86** [demilich1/metastone#322]
https://github.com/demilich1/metastone/blob/cd962746ab401eaa43ad18ac0e38b413d7a49f90/cards/src/main/resources/cards/the_grand_tournament/druid/token_sabertooth_tiger.json

On http://hearthstone.gamepedia.com/Tiger_Form it says it's Tiger Form

On http://www.hearthpwn.com/cards/35366-sabertooth-tiger it's Sabertooth Tiger

Inside hearthstone card descriptions it's OG_044c "Sabertooth Tiger"

Not sure how it's displayed in actual game client (don't have Fandral).

So what's the real name?

**Comment by DominusMaximus** [comment]
It used to be Tiger Form, but was later changed to Sabertooth Tiger.
