### ISSUE TITLE
[Request] ETA new release?

### ISSUE THREAD

**Issue by cydlord** [demilich1/metastone#325]
Are there any plans to push a new release? I'm not that knowledgeable at coding and maybe I'm just too lazy to open a command window every time I want to open metastone. Having an .exe file for the latest version would be very much appreciated.

Thanks for all your hard work!

**Comment by mayuso** [comment]
It's been 5 months and over 150 commits since 1.2RC3. 

I don't really know what @demilich1 and/or @webadict are planning to do, but I think releasing 1.2 soon ^TM should be considered. I don't know what they base release times on, maybe there's still work to do, some implementations missing or a bug that's still not fixed, but at least getting a RC4 sounds like a good idea in my opinion.

**Comment by webadict** [comment]
I am fine with 1.3 being released. There's been several fixes, and it seems fairly functional from this point on. I've been super busy with work, so I haven't really pushed the issue, but it's really up to @demilich1 to release.

**Comment by mayuso** [comment]
Should 1.2 be skipped? We have lot's of changes since Release Candidate 3 but I don't know how to feel about skipping one version number. 

I guess it's fine, it'll probably feel like a "fresh start" after such a long time.

**Comment by demilich1** [comment]
I just published the 1.3.0RC1 release here on github.

By the way, 1.2.0 was not skipped, I uploaded it on my website: http://www.demilich.net/metastone/ and the version is identical to the 1.2.0RC3 build here on github. Basically the idea is to publish RC (release candidate) builds on github and when no more major bugs are found, we 'officially' release the version. I could have uploaded an official 1.2.0 release on github as well, but it feels a little bit wasted when you consider the binaries are identical with the latest RC build.

**Comment by mayuso** [comment]
> Basically the idea is to publish RC (release candidate) builds on github and when no more major bugs are found, we 'officially' release the version.

I like the idea of publishing final ("official") versions on the website.

I am used to the linux version system, where they release "release candidate" versions from 1 to 7 and then release the final version (the last release is only final, not release candidate and final).

But again, I like your version numbering for metastone more, that way we can identify the last release candidate as final release here on github, while we don't need to use the sowewhat ugly "release candidate" tag for website final version. I like it.

**Comment by webadict** [comment]
Yeah, sorry I haven't been helping out much recently. I kinda got a
developer job using what I learned from this project, surprisingly. I'll
certainly help out when new cards come out, but I have a lot less time than
I used to have, so it will definitely take a lot more time.

**Comment by demilich1** [comment]
>  I kinda got a developer job using what I learned from this project, surprisingly.

That's great news! I would have hired you too if I had a company ;) Do you enjoy your new job?

**Comment by webadict** [comment]
Yeah, they're pretty cool. It's nothing as fun as this, but I'm doing a lot
of web development, and the amount I'm learning is staggering, but it's
weird I could really apply what I was doing here into a real job... It's
kinda surreal that I didn't realize how much I learned from this. It never
seemed like that much...

Anyway, just wanted to let you guys know I am still here, but I'm a lot
busier than I was.

**Comment by DominusMaximus** [comment]
Good to hear webadict. It seems coding Kazakus and Mayor Noggenfogger sharpened your powers! You improved Metastone tremendously. It's in a very good state.

**Comment by mayuso** [comment]
Congrats webadict. 

It sounds really cool if you say "I got a work thanks to metastone" hahaha. I am currently working, but I am considering adding all my open source work to my CV in the future, and your case is great motivation to do so.
