### ISSUE TITLE
Webspinner should be a Beast, is not currently

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#33]
Not really much else to say here.

**Comment by SirFatCat** [comment]
Another small thing, I happened to fix it myself on the previous version thinking it might be fixed in the next (as I saw that 0.9.9 was in progress I didn't think to mention it), but Harvest Golem should be a Mech, is not currently one.

**Comment by mayuso** [comment]
I will check this as soon as i get home (7 to 8 hours from now).
