### ISSUE TITLE
Need some help with a custom card

### ISSUE THREAD

**Issue by Watermelon86** [demilich1/metastone#330]
I've been trying to code in a custom card 
 that is returned to your hand if something attacks it. The idea of it was to be an effective trading tool for control decks.
![puntable podling - common](https://cloud.githubusercontent.com/assets/25935567/23180178/8489fa28-f83e-11e6-989e-255700fefb96.png)

I was able to get most of the code to function properly, however once the card has been returned to your hand, whatever attacked it can attack again even if does not have Windfury. I'm guessing this is because the game does not consider the attack as resolved because the target was removed before it could be hit.

In an atempt to fix this I tried to make it also freeze whatever attacked it, but it just ended up freezing itself before returning to your hand.

Heres the code that I have right now:
```
{
	"id": "minion_puntable_podling",
	"name": "Puntable Podling",
	"baseManaCost": 2,
	"type": "MINION",
	"baseAttack": 4,
	"baseHp": 2,
	"heroClass": "ANY",
	"rarity": "COMMON",
	"description": "Can't attack heroes. Whenever this minion is attacked, return it to your hand.",
	"trigger": {
		"eventTrigger": {
			"class": "TargetAcquisitionTrigger",
			"actionType": "PHYSICAL_ATTACK",
			"sourcePlayer": "OPPONENT",
			"hostTargetType": "IGNORE_OTHER_TARGETS"
		},
		"spell": {
			"class": "MetaSpell",
			"spells": [
				{
					"class": "AddAttributeSpell",
					"target": "EVENT_TARGET",
					"attribute": "FROZEN"
				},
				{
					"class": "ReturnMinionToHandSpell",
					"target": "SELF"
				}
			]
		}
	},
	"attributes": {
		"CANNOT_ATTACK_HEROES": true
	},
	"collectible": true,
	"set": "CUSTOM",
	"fileFormatVersion": 1
}
```
I'm pretty sure the line `"target": "EVENT_TARGET",` in the first half of the MetaSpell is what's causing the issue, but I'm not sure what the proper target syntax would be in this case and I can't seem to find a list of possible targets under the documentation section on here.

Does anyone know how I might be able to fix this?

**Comment by DominusMaximus** [comment]
This is the best I could come up with. Instead of returning the Podling before the attack damage is dealt, I allow the attack to complete by setting the Podling's attack to zero and giving it Immunity. This ensures the Podling survives and that the attacking minion receives no damage. Most importantly, it allows you to use the "AfterPhysicalAttackTrigger". 

{
	"id": "minion_puntable_podling",
	"name": "Puntable Podling",
	"baseManaCost": 2,
	"type": "MINION",
	"baseAttack": 4,
	"baseHp": 2,
	"heroClass": "ANY",
	"rarity": "COMMON",
	"description": "Can't attack heroes. Whenever this minion is attacked, return it to your hand.",
	"triggers": [
		{
			"eventTrigger": {
				"class": "TargetAcquisitionTrigger",
				"actionType": "PHYSICAL_ATTACK",
				"sourcePlayer": "OPPONENT",
				"hostTargetType": "IGNORE_OTHER_TARGETS"
			},
			"spell": {
				"class": "SetAttackSpell",
				"target": "SELF",
				"value": 0
			}
		},
		{
			"eventTrigger": {
				"class": "TargetAcquisitionTrigger",
				"actionType": "PHYSICAL_ATTACK",
				"sourcePlayer": "OPPONENT",
				"hostTargetType": "IGNORE_OTHER_TARGETS"
			},
			"spell": {
				"class": "AddAttributeSpell",
				"target": "SELF",
				"attribute": "IMMUNE"
			}
		},
		{
			"eventTrigger": {
				"class": "AfterPhysicalAttackTrigger",
				"targetPlayer": "SELF",
				"targetEntityType": "MINION",
				"hostTargetType": "IGNORE_OTHER_TARGETS"
			},
			"spell": {
				"class": "ReturnMinionToHandSpell",
				"target": "SELF"
			}
		}		
	],
	"attributes": {
		"CANNOT_ATTACK_HEROES": true
	},
	"collectible": true,
	"set": "CUSTOM",
	"fileFormatVersion": 1
}

**Comment by webadict** [comment]
The question is: Does it die if it doesn't survive the attack?

I see a few of the issues with the card, as is. Right now, it will return when ANYTHING your opponent controls attacks. Otherwise, this is actually a tricky card. It might be doable if it DOES die, but without dying, this is tough.

**Comment by Watermelon86** [comment]
My original thought was that it would be returned without it or what attacks it being damaged, so your opponent would have to use their Hero or a minions attack each turn to delay the Podling until it could be removed via Spell/Hero Power/Battlecry or just let it stay on the board and let you trade with it.

**Comment by webadict** [comment]
```
{
	"id": "minion_puntable_podling",
	"name": "Puntable Podling",
	"baseManaCost": 2,
	"type": "MINION",
	"baseAttack": 4,
	"baseHp": 2,
	"heroClass": "ANY",
	"rarity": "COMMON",
	"description": "Can't attack heroes. Whenever this minion is attacked, return it to your hand.",
	"triggers": [
		{
			"eventTrigger": {
				"class": "TargetAcquisitionTrigger",
				"actionType": "PHYSICAL_ATTACK",
				"hostTargetType": "IGNORE_OTHER_TARGETS"
			},
			"spell": {
				"class": "MetaSpell",
				"spells": [
					{
						"class": "SetAttackSpell",
						"target": "SELF",
						"value": 0
					},
					{
						"class": "AddAttributeSpell",
						"target": "SELF",
						"attribute": "IMMUNE"
					}
				]
			}
		},
		{
			"eventTrigger": {
				"class": "AfterPhysicalAttackTrigger",
				"hostTargetType": "IGNORE_OTHER_TARGETS"
			},
			"spell": {
				"class": "ReturnMinionToHandSpell",
				"target": "SELF"
			}
		}
	],
	"attributes": {
		"CANNOT_ATTACK_HEROES": true
	},
	"collectible": true,
	"set": "CUSTOM",
	"fileFormatVersion": 1
}
```

Here's a better version. Condenses the triggers, and adds a a few cases in case of things like Misdirection or Betrayal, which should send it back based on the description.

**Comment by webadict** [comment]
Or... no Betrayal, would still kill it with mine, I believe. It's about 75% chance that's true.

**Comment by DominusMaximus** [comment]
Just tested Betrayal. It kills the Podling, which seems correct, since Betrayal's damage is similar to an Elven Archer's 1 damage Battlecry. No combat occurs.

**Comment by webadict** [comment]
But it is technically attacked. Not sure how you'd want that to go.

**Comment by Watermelon86** [comment]
That works good for the testing I want to do. Thanks for the help!
