### ISSUE TITLE
Grimestreet Protector Bug

### ISSUE THREAD

**Issue by Watermelon86** [demilich1/metastone#332]
When I played Grimestreet Protector in play mode it gave the adjacent minions Taunt instead of Divine Shield.

**Comment by webadict** [comment]
This should be fixed in the next release.

**Comment by mayuso** [comment]
The current code has this fixed ( #328 ), so yes, the next release will have this issue fixed.

**Comment by demilich1** [comment]
Actually, it already should be in the 1.3.0 release
