### ISSUE TITLE
[Question] I have added a new Hero to the HeroClass.java. How do I add the graphic for this hero, Heropower/Portrait?

### ISSUE THREAD

**Issue by Boso101** [demilich1/metastone#343]

**Comment by webadict** [comment]
Well, there's kind of a problem with that. You see, the Hero portraits are hardcoded in. So... There's not really a way to do that just yet, without modifying another file. Same goes for hero powers as well. It's possible to add this feature eventually, but it would be a much lower priority. That said, I'm not against it, and it'd be nice to see.

**Comment by Boso101** [comment]
Okay, so basically all I can do for now is edit the existing ones? oh well good enough.

**Comment by demilich1** [comment]
Well if you added code to the HeroClass.java, you already modified the source code. There is nothing stopping you from modifying additional files, right? Like @webadict already mentioned, right this is the only way, we don't have a way to define a new hero class as pure data.
