### ISSUE TITLE
King's Elekk seems to be broken?

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#35]
Tried to use it just now, it revealed a Piloted Shredder, and instead gave me a Ram Wrangler, or it might have copied the one in my hand. 
http://i.pomf.pl/vqibro.png

Tried it again, seems that it just draws 1 card rather than the card revealed. That's my guess, anyways.

**Comment by webadict** [comment]
King's Elekk was improperly calling the drawCard method. This will be fixed in the next PR.
