### ISSUE TITLE
Can't get my cards to show up in the client.

### ISSUE THREAD

**Issue by Chibi1234** [demilich1/metastone#351]
So I was creating cards using Metastone back in the day and they all used to work fine.

I decided to install Metastone again now after a couple months and I saw that the ''cards'' folder had been remade into a zip file, But whenever I tried making some cards inside of the zip file they didn't show up in the client, They didn't show up. I tried to extract the folder and put my custom cards in there and delete the original zip, That didn't work either. I think it has something to do with the lack of the ''id'' thingy.

Am I missing something?

-Sincerely, That one dude that made the custom SC2 card pack and wrote the first draft of the ''Creating Cards'' wiki page.

**Comment by Muhframos** [comment]
Hmmm... Where is the RAR located? Maybe you're on the wrong folder? The cards folder should be inside the Metastone folder inside documents or wherever you installed it.

**Comment by webadict** [comment]
Yeah, check your My Documents folder for a metastone folder.

**Comment by Chibi1234** [comment]
Ah- I'm stupid. Thanks guys, Got it to work now 👍
