### ISSUE TITLE
Compiling returns empty app

### ISSUE THREAD

**Issue by victorgrego** [demilich1/metastone#360]
So, I've followed all instructions on main page and tried to compile. The problem is: the compiled app has an empty interface. Any thoughts?

Oh, I've also downloaded the install file and metastone has an empty UI

![image](https://user-images.githubusercontent.com/6922949/27015213-f8982862-4ec5-11e7-88ab-d03ce11ef4e5.png)

**Comment by demilich1** [comment]
Unfortunately that bug affects some users of MetaStone and we don't know how to change the code to fix this bug. However, there was at least one another user who encountered that bug and he was running a Surface. He said that switching to 'Tablet Mode' fixed the problem for him. For more details, please see this issue #159 (interesting stuff is at the bottom)

**Comment by victorgrego** [comment]
Thank you for the fast answer! Well, that is weird. I've run in the same trouble as cited in #159. Will try tablet mode by now, and try a fix when i get pissed.
