### ISSUE TITLE
Can't Add A new Race!

### ISSUE THREAD

**Issue by percy896** [demilich1/metastone#366]
Here's the issue and here's what a bunch of us need help with:

When adding and editing cards, you simply go in and add a new .json file, reload Metastone, and poof, it's there and fully-functional (as long as you've coded it correctly). This does not happen with adding new races, probably because they are not in .json files. They are in .java files. Some of us don't understand what you have to do differently to update the .java file, besides edit the text and add a new race to the list. We don't know how to "recompile" because we are less familiar with java. Can anyone please help us? Thank you!

**Comment by percy896** [comment]
Anyone? Thank you.

**Comment by webadict** [comment]
Well... I wish it were as easy as it sounds. But right now, it's just not high enough priority to split it. There are compilation instruction on the front page, and if you list what you've done so far, it might be easier to help you get this compiled

**Comment by webadict** [comment]
Closing issue. The answer is that you need to program it in, unfortunately.
