### ISSUE TITLE
Baron Rivendare works even if it dies at the same time as another deathrattle

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#38]
Pretty sure it doesn't work that way, see:
http://gaming.stackexchange.com/questions/234216/what-happens-if-baron-rivendare-and-dreadsteed-die-at-the-same-time

**Comment by webadict** [comment]
This is the same issue as the death resolution rewrite. Currently, all
minions are removed one at a time instead of in groups. This will need to
be one of those things to be fixed.

**Comment by webadict** [comment]
I did a rewrite of deathchecking. I think it might fix this problem, but I'll have to test it later tonight.

**Comment by webadict** [comment]
This should be fixed as of now.
