### ISSUE TITLE
Is the website dead?

### ISSUE THREAD

**Issue by bakublade2002** [demilich1/metastone#383]
Will the website http://www.demilich.net/metastone/index.html 
Ever been updated? 
Plus
I'm not a programmer but really enjoyed that simulator.
Is there a simple exe file with new cards?
I don't know how to compile things.

**Comment by nfactor13** [comment]
If someone is still working on updating the simulator part, I would be happy to make a small donation.  I had a long while back but hadn't seen any new content in a very long time and assumed it was dead.  I mostly like to use the theorycrafting features.

**Comment by doctorpangloss** [comment]
@nfactor13 There's my fork, that has 100% of Hearthstone implemented, at https://github.com/hiddenswitch/Spellsource-Server . Check it out!

**Comment by nfactor13** [comment]
Hi, doctorpangloss.  You have a nice program, and I can see you put in a lot of work.  From what I can see, it appears to allow you to play the Hearthstone cards against another bot or human, but that's not the feature I was curious to use from Metastone.  I mainly use the simulator to run thousands of games against various builds or sets of builds and look for differences in the win percentage.  If you have that feature incorporated, I didn't see it.  Otherwise, nice job on the transfer.

**Comment by doctorpangloss** [comment]
@nfactor13 

Join our chat at https://discord.gg/t5ctkUT and I'll show you exactly how to do that.

**Comment by doctorpangloss** [comment]
You can take a look at simulation code partially documented here:

https://github.com/hiddenswitch/Spellsource-Server/tree/master/cluster

**Comment by webadict** [comment]
Hey @nfactor13. I do apologize. I think @demilich1 is incredibly busy, unfortunately. He's a busy guy.

As for me, I've been working at my new job and I've moved away from this project. Unfortunately, I just don't have the time or motivation to work on this anymore. I've been working on other projects, namely podcasting and all that jazz. I did have a lot of fun working on this, and I'm glad to have used the experience and learning I got from here towards my new job, but alas, it has stolen most of my extra time that I used to have.

I think moving to a branch of this project or a new project might inevitably be the best idea. Unfortunately, the two main contributors just don't have the time, and there doesn't appear to be anyone else stepping up to take up the mantel.

Perhaps in the future, I might be able to help, but until then, this is the foreseeable condition. I don't want to get hopes up about it. I figured I'd give you an answer though. I think moving towards @doctorpangloss's project might be the best move.

Regards,

Webadict.

**Comment by nfactor13** [comment]
That's all right.  Thanks for all your contributions, and I'm glad it was a good experience for you.

I'm happy to learn something new myself, and perhaps going with doctorpangloss's attempt will be a good stimulus that way.  Take care, and good luck on the new ventures.

**Comment by webadict** [comment]
Closing this issue. Not entirely sure how it landed.
