### ISSUE TITLE
[Bug] Mirror Entity problem with Faceless

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#41]
Difficult to point it towards a single thing so I'll just describe the below situation:
http://i.imgur.com/RoELLAu.png

So I had a Water Elemental on the field with Mirror Entity while he had nothing at the start of his turn. He plays a totem, Searing Totem, and everything went kind of fast but I would assume it was okay and nothing triggered as he'd used his hero power earlier in the game several times. Then, he plays Faceless Manipulator on my Water Elemental, and so Faceless Manipulator changes into Water Elemental. Somehow, Mirror Entity triggers during all of this but does not give me a second Water Elemental. It just disappears. I first thought it was a card that just killed it somehow but looking at his mana 5+2 = 7 and he only has 1 usable crystal left on turn 8, so I'm pretty sure he didn't play anything else.

**Comment by webadict** [comment]
Found the issue. Transform minion spell removes the minion from play and adds a new minion. This is the same result for any summoned Transformed minion (Druid of the X, Faceless Manipulator). The issue is the spell, not the Secret, so I'll check it out later.

**Comment by webadict** [comment]
Well, more information:

The secret trigger layer basically only tries to target the card that was played... This is only an issue for cards that transform themselves on play. So, anything that would affect the minion... Only affect the destroyed one.

This means that Mirror Entity, Snipe, Sacred Trial, and Repentance will all target the incorrect unit.

**Comment by webadict** [comment]
Alright, I believe I have this fixed in the next PR.

I created a new method that no longer summons an extra minion on board (Since I believe there were probably other issues that could happen, like procing Knife Juggler twice, leaving transformed minions in the graveyard, etc.) Transformed minions should now correctly enter the summon stack when they transform at summon.

**Comment by webadict** [comment]
Wow, you probably don't care, but I also fixed a whole host of other issues while looking at Transformations. There were... a lot of issues this was causing internally that would rarely ever make a difference...

**Comment by webadict** [comment]
This should be checked to make sure it is completely fixed. I believe it is, but there might be a case or two I'm missing.

**Comment by SirFatCat** [comment]
I'll close it for now.
