### ISSUE TITLE
[Bug] Unearthed Raptor Bugged

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#43]
Whenever you copy a Deathrattle effect with Unearthed Raptor, it will trigger it at the same time as copying it into the Raptor. It happened with Nerubian Egg and Raptors who copied a Nerubian Egg so I'm not sure if it happens for other effects but I would assume it does.

**Comment by webadict** [comment]
This was fixed in the latest PR. It's the same bug as Darnassus Aspirant.
Battlecries were triggering deathrattles accidentally. This is now fixed
though.

**Comment by SirFatCat** [comment]
I see, I'll go ahead and close it then.
