### ISSUE TITLE
Add option to build arbitrary decks

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#44]
Add the moment all decks built in MetaStone must follow the standard Hearthstone construct rules:

Only 1 of each Legendary and 2 of each other card.

Several users requested the option to lift those restrictions to test arena decks or just build fun decks (30 Unstable Portals anyone?).

I don't like the idea of just removing the checks for all decks, at is very useful to have the same rules as in the actual game. However, we could add an opt-in checkbox when creating a new deck, maybe labeled 'Ignore deck-building rules' or something like that. The ideal implementation would also display a small icon or label next to each deck in the deck overview which does not obey the standard rules. This way, users could distinguish between fun and serious decks at one glance.

**Comment by webadict** [comment]
Technically, they can create decks like that by just making the deck manually. I do this for random testing by using 15 Burgles and 15 Unstable Portals.

But, yeah, I kinda agree.

**Comment by Chibi1234** [comment]
But what if... we lifted the card limit aswell! (100000000000000000 Unstable portals! BWAHAHAHAH!)

**Comment by webadict** [comment]
The hard card limit in Hearthstone is 60. However, Netastone is bugged to
use 30 right now, so while lifting the limit will be done, there will still
be a hard limit of 60.

**Comment by Chibi1234** [comment]
oh okie... but what if we could use under 30 cards! 
My deck list if so:
1x Divine Spirit
1x Inner Fire
1x Deathlord
2x Innervate

**Comment by webadict** [comment]
So... I've gotten this implemented, but I'm conflicted: Do I allow 0 card decks to exist? I mean, if you want to play that way, I've got it working (Mulliganing is a bit weird, but it's whatever.) I don't see the harm in it, but that's just me. Unfortunately, this means that the deck creator no longer warns about too many or too few cards while building an arbitrary deck.
