### ISSUE TITLE
Wrong token positions: Tuskarr Totemic and Imp Gang Boss

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#45]
Both of these minions spawn their tokens always on the far right side of the board. The correct position would be next to themselves (should be a simple .json fix)

**Comment by webadict** [comment]
Technically, there is only two token placement types in Hearthstone. Either
minions spawn next to their source or they don't. Whenever more than 1
token is summoned, the summoning pattern should be right then left then
right then left etc. This can actually be seen in every single instance of
multiple minion summoning relative to the source, and especially Onyxia.

So really, this is a bigger issue as well.

**Comment by demilich1** [comment]
You are right, but this issue only affects Onyxia really. We can specify where the token spawns for all other instances and it works just fine. I agree we should probably change this in the future, but for now the easy fix is to specify the correct token positions for those two cards.

**Comment by webadict** [comment]
True. This was just something I noticed during the Ragnaros vs. Nefarian Tavern Brawl. There was a special battlecry minion that summoned 3 minions, which surrounded the original summoner in the same fashion (Instead of all to the side, like I thought would happen.)

I've fixed this and will include it in the next PR, along with Ram Wrangler. It's likely there's a few others that don't summon next to their source.

**Comment by webadict** [comment]
These are mostly fixed. Technically, there should be a rewrite of the Summon spell, so that everything summons correctly, but until then, I fixed the remaining classes to work how they should.

**Comment by webadict** [comment]
This should now be pseudo-fixed in the next PR until a rewrite of the summon command is done.

**Comment by webadict** [comment]
Due to Summoning Stone's odd summoning procedure (Technically, it's not TOO weird, but Hearthstone programmed it weird), I'm gonna close this issue. It's basically solved.
