### ISSUE TITLE
[Bug] Secretkeeper + Mysterious Challenger

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#46]
Secretkeeper currently gains the bonuses from the secrets played via Mysterious Challenger, while it shouldn't as Secretkeeper specifically states that the secrets must be played in order to gain the bonuses.

**Comment by webadict** [comment]
Secretkeeper should no longer be buffed by Mysterious Challenger or Mad Scientist in the next PR. If an event needs to be added for Secrets coming into play through Mad Scientist or Mysterious Challenger (A card is added or what-not), this can be added later.
