### ISSUE TITLE
Sir Finley Mrrgglton offers starter hero power

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#47]
Sir Finley Mrrgglton is currently discovering the hero power you start off with as one of the options. From what I've read he should only discover 3 out of the other 8 hero powers.

**Comment by webadict** [comment]
I was waiting to see how he works when you have a different basic Hero
Power than what you start with. There was a little confusion on the matter.

**Comment by webadict** [comment]
Testing Finley has shown that he grants you the chance to grab any basic Hero Power except for the one you currently have. It's very likely this includes your basic Hero Power when you have an upgraded one, so I'll add this to the list of things to fix.

**Comment by webadict** [comment]
This is now fixed in the next PR.

**Comment by webadict** [comment]
This should be closed, as it is fixed now.
