### ISSUE TITLE
Hungry Crab is acting wierd!

### ISSUE THREAD

**Issue by Chibi1234** [demilich1/metastone#51]
Whenever the AI plays a Hungry Crab with 2 or something like that murlocs, one of the murlocs dies (Like normal) but the Hungry Crab gains +6/+3 and i dont know why

**Comment by webadict** [comment]
I can't seem to find this issue. There shouldn't be any reason for that, since the minion has nothing programmed into it that would allow something like that, and I don't believe the AI are allowed to do anything that you couldn't do. Maybe there were other buffs on the field or something else was played after that? I'd need to see this happen in order to figure out what's wrong.

**Comment by webadict** [comment]
If you can recreate that scenario, let me know what steps you took.

**Comment by Chibi1234** [comment]
I was playing with the AI Murloc deck vs Murloc deck and on turn 3 he played the murloc warleader, right after that i played the murloc warleader, after that he got the bluegill, he attacked with the bluegill to kill my warleader and then came the hungry crab and gained +6/+3, Maybe its something with the Warleaders buffs applying to crabs :I

**Comment by webadict** [comment]
Hmm... I can't seem to replicate it. There doesn't seem to be any issue on my end. It shouldn't interact with Hungry Crab since its a Beast, and not a Murloc, so I'm not sure why it would do that.

**Comment by SirFatCat** [comment]
I'm also not getting this bug, just tried to replicate it as well trying to destroy the other player's warleader with the hungry crab while having Bluegill and the other Warleader on my side of the board as well as the situation you just described, and it didn't work for me in either case.

**Comment by Chibi1234** [comment]
Oh i fixed it but it seemed to be a problem with my installation (Somehow), the card was at normal (When i inspected it yesterday) and its still the same now when i have redownloaded Metastone but the bug thingy doesn't work

*Closes Issue*
