### ISSUE TITLE
[Improvement] Arttwork

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [demilich1/metastone#56]
Hey all,

I am in second year CompSci at ULB in belgium and our year project is acyually simulating hearthstone with socket programming and no singleplayer support, all of it in QT haha, I'm in charge of game programming and cards and already created a couple of unique cards with artwork. It was quite easy to add the images into a sample card collection if already done.

So i was thinking, framework support for the artwork files, which can all be found here: http://imgur.com/a/qLi7G#0 , could potentially be added already no?
To be seen would be:
[ ] Format they are saved in.
[ ] Reference to them via json files or other.
[ ] Any potential mismatch would have to be seen one by one

Cheerio mates :D

**Comment by demilich1** [comment]
This is more of a legal issue than a technical one. It is pretty simple to assign an image to each card, but I don't want this done. All of the artworks are copyrighted by Blizzard. At the moment Blizzard tolerates the various Hearthstone simulators, but this might very well change when an application tries to re-create the Hearthstone playing experience

**Comment by Mixone-FinallyHere** [comment]
Ahhhh I see, thanks for clearing that up :D

2015-12-23 18:28 GMT+01:00 demilich1 <notifications@github.com>:

> This is more of a legal issue than a technical one. It is pretty simple to
> assign an image to each card, but I don't want this done. All of the
> artworks are copyrighted by Blizzard. At the moment Blizzard tolerates the
> various Hearthstone simulators, but this might very well change when an
> application tries to re-create the Hearthstone playing experience
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/demilich1/metastone/issues/56#issuecomment-166950254>.
>



-- 
Miguel Terol
