### ISSUE TITLE
[BUG] Prophet Velen doesn't seem to be working with Keeper of the Grove

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#57]
Title, it might not work with other cards like it as well. The original issue was that the card wasn't working at all, but I think it might just have been silenced in the game I was playing. I just tested it however and it doesn't seem to work with Keeper.

**Comment by webadict** [comment]
Umm... That's not a bug? Prophet Velen should only double the damage and healing from Spells and Hero Powers?

**Comment by SirFatCat** [comment]
My mistake, then. I initially opened the issue for a different reason and forgot that it said only spells/hero powers when looking it over. Closed.
