### ISSUE TITLE
[BUG] Huge Toad isn't working properly

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#58]
It should be dealing 1 damage to a random enemy, not all enemies.

**Comment by webadict** [comment]
This should be fixed in the current iteration, I believe.

**Comment by SirFatCat** [comment]
Oh, I might not have updated on this computer. I'll try it again after installing it once more.

**Comment by SirFatCat** [comment]
Just tested it, it is still working that way.

**Comment by webadict** [comment]
It shouldn't be. It was fixed 3 weeks ago, which should have been put into
the newest version...

**Comment by SirFatCat** [comment]
Well, be sure to test it when you get back from your vacation and if it's fixed tell me, not sure why it's not working for me, I'm pretty sure I'm using the newest release on the github.

**Comment by webadict** [comment]
It's fixed from everything I can see. Maybe the wrong version was uploaded? I haven't checked on current web version, but it should be fixed.

**Comment by SirFatCat** [comment]
This is the current version, yes?
https://github.com/demilich1/metastone/releases/tag/0.9.9a

**Comment by webadict** [comment]
That looks like it. And it's got the correct file. If you check the cards/league_of_explorers/huge_toad.json card, if it has the line `randomTarget": true` then it should work. Maybe your JSON file is wrong?

**Comment by demilich1** [comment]
It may also be possible that you got two versions of MetaStone installed on your PC (maybe in different folders?). Somehow you seem to be running an outdated version, as I just double-check and downloaded the version you linked. Huge Toad works correctly for me.

**Comment by SirFatCat** [comment]
Maybe I need to uninstall Metastone and reinstall it, as just trying to run the installer on the 0.9.9a page doesn't seem to give me the updated version of Huge Toad (and possibly other things).

**Comment by webadict** [comment]
I just ran the installer on the 0.9.9a page. I did NOT have the issue.

I don't know what to tell you, man. It's fixed on all of my versionss.

**Comment by SirFatCat** [comment]
That's so weird. I've run the installer multiple times and my Huge Toad .json file does have what you told me, so I'm not sure what the problem is. I don't think it's running from a different source either, and to check I ran the .exe file that shares the same directory with the Huge Toad .json file and it still is broken for me. I guess I'll wait until the next update is done and if it's still broken I'll look into it more. I'll also try not to report any bugs unless I know for sure they're not from previous versions.

**Comment by mayuso** [comment]
"I'll also try not to report any bugs unless I know for sure they're not from previous versions". IMHO, it´s better to have some "False Positives" than an unreported Bug. In other words, it is better to make a mistake reporting a bug that is actually not a bug than not reporting a real bug. Not sure if I am explaining that well haha.

**Comment by SirFatCat** [comment]
I agree, I just meant that I'll be a bit more careful from now on considering the fact that this issue is still present no matter how I update. :)

**Comment by mayuso** [comment]
I don´t think an extra issue (Or 50 extra issues) is a problem. I´d love to have people reporting bugs on my own projects, usually, more Issues opened (Even if mistakes), is a good sign, means the project is alive and people are interested on it.
