### ISSUE TITLE
[BUG] Misdirection not working with Kezan Mystic

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#59]
It doesn't seem to be working when stolen with Kezan Mystic.

**Comment by webadict** [comment]
I think Misdirection is currently broken anyhow... sooo yeah. I'll check it
out some time when I get back from vacation.

**Comment by webadict** [comment]
Hahaha... I think I figured out this issue. Completely by accident.

**Comment by webadict** [comment]
Well, that's a dumb fix.

**Comment by mayuso** [comment]
What fix? XD

**Comment by webadict** [comment]
Misdirection was only working when your own minions attacked your own Hero. Which, you know, isn't the point of the card. So, Misdirection should now work on all minions (As the card dictates.)
