### ISSUE TITLE
[BUG] Avenge doesn't seem to be working sometimes

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#60]
It might be targeting the minion that died and not applying it to any other minions?

**Comment by webadict** [comment]
It is currently targeting the dead minion occasionally. I thought this was
fixed in the deathrattle processing fix, though...

**Comment by SirFatCat** [comment]
As I said in one of the other bug reports, I'm currently using the previous version of the client so it's possible that this might be fixed. I'll leave it open for a while and if I don't encounter the problem again (or someone else confirms that it is working properly), I'll close the thread.

**Comment by webadict** [comment]
I did a few tests with Avenge, and it seems like it should be fixed after the deathrattle change in 0.9.9. The fix should've been making all minions that were pending death be unable to be targeted by random abilities like deathrattles (which Avenge functions similarly to.) So, you should be fine closing this issue, unless you've seen it pop up again.

**Comment by SirFatCat** [comment]
Sure, I'll be fine with that. I tried it again just now and it doesn't seem to work that way anymore, how weird.
