### ISSUE TITLE
[BUG] Rampage not working with Djinni 

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#61]
I think there might have been another spell that didn't work with it, but I just tested it and Rampage doesn't work on the most current version.

**Comment by webadict** [comment]
This might be fixed with the spell trigger update, but I'm not sure. It
should work, so I'll have to check it out.

**Comment by webadict** [comment]
My guess is that it's checking the condition of the spell before
activating. Testing with Backstab and Rampage and different injured states
would verify (one injured and one uninjured Djinni.)

If that's the case, the spell trigger update should fix that.

**Comment by SirFatCat** [comment]
Backstab is working, however. Just tried it.

**Comment by webadict** [comment]
It's as I suspected. If a spell is unable to target Djinni, then the spell fails, instead of overriding the conditional targeting.

This means that when using Backstab on your own minion, it should deal 2 damage to the Djinni despite injured status. I'll see what I can do.

**Comment by webadict** [comment]
Alright, that was actually a really easy fix. Next PR will fix this issue.
