### ISSUE TITLE
[BUG] Astral Communion

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#62]
When you use it, it is supposed to give you 10 usable mana crystals. Currently, it gives you 10 unusable ones.

**Comment by webadict** [comment]
Easy fix. Just needs the "fullManaCrystals": true added to the Modify Max
Mana spell. You can fix it or wait until I get back.

**Comment by SirFatCat** [comment]
I don't know how to add stuff to the github so I'll let you manage it.

**Comment by webadict** [comment]
Fixed in the next PR.
