### ISSUE TITLE
Simulation performance issue

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#64]
I just received a mail from a MetaStone user:

>I've been away from Hearthstone since September and updated my local code today.  To my surprise, I've noticed that some simulation mode matches now take an exceedingly long time.  I initially feared deadlock, but simulations always complete.  There are several new decks that appear to be consistent offenders, but the problem is not limited to decks with new cards.  None of the decks I tested in September presented performance issues, but a few do now.

>I implemented a batch simulation mode locally and roughly 1 out of every 15 simulations that I tested takes over 4 minutes.  The slowest deck by far is rank_1_legend_na_reno_dreadsteed.json, which was introduced with League of Explorers, while one of the slowest pre-LoE deck is tsafys_top_100_legend_shammy.json.  I initially suspected that my batch mode is incompatible with the latest code, but when I removed all of my local additions and ran a normal GUI simulation of rank_1_legend_na_reno_dreadsteed vs. tsafys_top_100_legend_shammy, I logged a 2 hr, 12 min run!  Most of the time was spent following game 96/100.

>Please let me know whether you're able to reproduce the issue at your end.  This should give us a clue regarding what should be investigated next.

I also noticed a slowdown personally, but I am not able to pin point the issue right now. If anybody got an idea which code takes long to execute, please post here. I would be happy to optimize it; otherwise I will start profiling myself when time allows it. For me this is a rather serious issue, as MetaStone is nearly unusable when 100 games take 2 hours to simulate.

**Comment by webadict** [comment]
If they did GSV, I could maybe beleve it. Those AI are slooooow for
simulation. I think 2 hours for 100 simulations might be a little much, but
if there was some sort of issue with the AI getting stuck, that might cause
it.

**Comment by demilich1** [comment]
Well, GameStateValue is of course much slower than i.e. PlayRandom, but this is still a new issue. Version 0.9.8 does not have those extremely long games, when I choose 100 games with GSV in 0.9.8, it always completes in 20-40 sec on my machine. However with 0.9.9 it happens quite often that the simulation does not finish within a timely manner

**Comment by webadict** [comment]
Maybe it's an issue with Discover actions? Since each choice is random when it's played, maybe it forks in 3 times as many game states to determine the optimal value? Adding a conditional statement similar to Battlecry actions might fix this?

**Comment by webadict** [comment]
Actually... probably MORE than 3! Maybe up to 27 times more! That would drastically increase processing time. Testing it now.

**Comment by webadict** [comment]
Yeah, there was very likely Discover action issues. I've given them a similar treatment to Battlecries. That speeds it up a bit, but I don't know if that's similar enough.

**Comment by webadict** [comment]
I'd say I've sped it up maybe 4-5 times more? Just a guess, but the change is in the PR.

**Comment by hugin7** [comment]
I submitted the above issue and noted that performance problems are not limited to new cards.  For example, tsafys_top_100_legend_shammy.json is a pre-LoE deck with no "Discover" cards, and I've seen it perform poorly in simulations against other old decks.  Simulations with older decks still complete in under 5 min, so LoE features are apparently the worst offenders, but 5 min is still a lot worse than older versions' 20-40 sec/100 games.

**Comment by webadict** [comment]
Random cards could generate Discover cards, so I would never discount it.

The biggest mechanic that significantly impacted actions was Discover, so
it's the most likely suspect (Additional action types were implemented to
allow for it.) I can't think of why older cards would avoid the slowdown
otherwise, since there weren't really any other changes that might make the
bot think as much.

**Comment by hugin7** [comment]
Good point - upon review of tsafys_top_100_legend_shammy.json, I noticed that Neptulon, which generates random murlocs, is present.  Following the release of LoE, the card can draw Sir Finley Mrrgglton, which has the "Discover" mechanic.  The probability of drawing Finley from Neptulon is about 29%, which explains why this older deck is impacted, but the issue is not as severe as for new decks with higher likelihood of playing "Discover" cards.

**Comment by webadict** [comment]
I'll test some other changes to see if I can get it back to near older
levels.

**Comment by webadict** [comment]
It's definitely much faster after the Discover change. I'd say that was probably the issue.

**Comment by hugin7** [comment]
Thank you for investigating.  Are you in position to commit your changes in the near future?

**Comment by webadict** [comment]
I've already requested a pull. Demilich just has to accept it. He's a busy
guy. If you'd like the changes immediately, you can compile my fork, though.

**Comment by hugin7** [comment]
Thank you.  I just grabbed the changes from your pull request and the performance gains are great.

**Comment by webadict** [comment]
Huzzay! I doubt I can speed it up much more from that without significantly altering the AI, so I think that's the best it'll be for a while.
