### ISSUE TITLE
[BUG] Blood Knight is hacking

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#67]
http://a.pomf.cat/lgrtzf.png

Only minion with divine shield on it was Argent Horserider. This happened, lol.

**Comment by mayuso** [comment]
That´s why BGH is autoinclude xD

**Comment by demilich1** [comment]
Are you sure you are running the most recent version right now? As some versions ago there was a bug where effects would be applied multiple times. You could try casting Velen's Chosen on Dragonkin Sorcerer for example, if it buffs it to anything greater than 6/10 then it is probably the old bug.

**Comment by SirFatCat** [comment]
Just installed the 0.9.9a installer today on my new computer. Dragonkin Sorcerer and Velen's Chosen work just fine on my end.

**Comment by webadict** [comment]
lol, it really does do that. What a filthy cheater.

**Comment by webadict** [comment]
Found the issue: The value multiplier was applying twice, so we were getting +9/+9 for each Divine Shield. It'll be fixed next PR.

**Comment by mayuso** [comment]
I have always wondered: PR stands for Public Release or Pull Request?

**Comment by demilich1** [comment]
It's 'Pull Request'

**Comment by mayuso** [comment]
Ok, thank you.
