### ISSUE TITLE
[Improvement] New Deck Formats

### ISSUE THREAD

**Issue by webadict** [demilich1/metastone#74]
With the announcement of new Deck formats (http://us.battle.net/hearthstone/en/blog/19995505/a-new-way-to-play-2-2-2016), new Deck archetypes are going to be needed. This should go hand-in-hand with #68 and #44 as well.

Some other improvements that would mesh well would be the ability to choose Deck Formats at the Deck Selection screen, the creation of a new Format, and the ability for a Deck to determine its Format.

**Comment by demilich1** [comment]
I would like to define the formats as .json, something like this:

standard.json
```
{
   "id": "format_standard",
   "name: "Standard",
   "sets": [
      BLACKROCK_MOUNTAIN,
      THE_GRAND_TOURNAMENT,
      LEAGUE_OF_EXPLORERS
   ]
}
```

This would also allow users to define custom formats which would be great for custom cards.

**Comment by mayuso** [comment]
There are 2 "new" formats, right? Standard (The new one) and Wild (New name, but is exactly like contructed nowadays). Is that correct?

**Comment by webadict** [comment]
For now, that's correct. But since the formats change, it's better to leave
it as a file that's easily editted. Plus, if a new format is ever created
(or you wanted your own for some reason) it'd be pretty simple to implement.

**Comment by mayuso** [comment]
Yes, I agree, I have been working hard this week and did not get much information about Hearthstone lately, that´s why I asked.

Definitely a .json file for each mode is the best idea :)

**Comment by webadict** [comment]
This is also important for random filters! Formats will only be able to conjure random cards from their own format, so... we'll have to do a rewrite of that...

**Comment by demilich1** [comment]
Right. Still, before doing all that, I propose to get version 1.0.0 ready with all those fixes and improvements you made. Then - as discussed in another thread - we could increment the version number to 1.1.0 and implement the Spring expansion and new formats (as I guess those will be release together?).

**Comment by mayuso** [comment]
Yes, they are planning to release them together, and I don´t think we will see it any time soon (Not in less that 6-8 weeks).

**Comment by webadict** [comment]
BOOM! Done!

It's not spectacular, but it does work! And that's all I care about at the moment. Someone else can fix the slightly bad layout it creates.

**Comment by webadict** [comment]
All I need to do now is make all random minions based off these formats... But at least you can select the right decks based on them.

**Comment by webadict** [comment]
Added CardCatalogues to use DeckFormats in next PR.
