### ISSUE TITLE
Undefined behaviour when cloning game state while a Battlecry is in progress

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#76]
I have to speak verbosely to explain this one.

You may have asked yourself: Why does MetaStone use EntityReferences everywhere, which are basically just a pointer to a Entity instead of passing plain old Java references to Entities directly? Well the sole reason for this is cloning.

To build any meaningful AI you have to be able to clone the entire game state (for example to try out different moves and check which one performs best). So there is one very important requirement to allow this: You should be able to call gameContext.clone() and get a completely independent copy of the current game state. All changes made to the copy should NOT affect the original game state in any shape or form. 

EntityReferences are a big step towards this goal, but more things have to be to be considered. All objects which are used inside the GameContext need to be either immutable or clonable. And whenever a .clone() method is implemented, the resulting instance has be to be completely independent of the source object. This may sound easy, but in practice it is very easy to forget to clone a list for example. The resulting bugs are incredibly hard to find, as the program compiles just fine and when using an AI which does not clone the GameState, nothing happens. However when an AI like GameStateValue is employed, undefined behaviour may occur.

Recently it came to my attention that there is indeed such a bug left. The problem is the 'environment' field of GameContext. It contains direct references to 'Entity' instances and when cloning the game state, those references still point the old context. Most of the time this is not a problem, as the entries in environment are all temporary and the HashMap should be empty at the end of each move. However, when performing a Battlecry action, this does not hold true. Basically when performing a Batllecry, the player behaviour is prompted for an action in the middle of another action. In this case, the SummonStack will contain a reference to the anew summoned minion.

I am not sure what the best solution for that issue would be. My gut feeling tells me that the 'environment' table itself is evil and should probably go away. However, it helps a lot with implementing some mechanics and I do not know alternatives for all of them (where do we store stuff like event targets, etc).

So we could instead put EntityReferences to environment (and all associated collections like SummonStack, etc). But this won't work right now, as some Entities exists SOLELY inside the environment table, i.e. it is not just a reference but the Entity itself. So we could introduce another List<Entity> in the GameContext, maybe called something like 'pendingEntities' which contains only Entities which do not live anywhere else (on the board, in the players hands or deck, graveyard, etc). Then the environment could contain EntityReferences, which can just be shared across cloned game states. 

If you have any thoughts on this topic, please let me know. Otherwise I might start implementing the solution mentioned above shortly.

**Comment by webadict** [comment]
Challenge accepted.

**Comment by demilich1** [comment]
Does this mean that you are working on this right now? Because it makes no sense when both of us are working on the same issue, so I would hold on for now.

**Comment by webadict** [comment]
I was planning to move Summon Stack to a Player-sided List, since the
Player would be the only one requiring access to their Pending Zone, and it
frees up some of the issues I was having for transformations (not that they
do much good now, but the Transformation field will also need to be
changed, as it also populates with an Entity.)

**Comment by demilich1** [comment]
I think this would not fix the issue at hand. Here is the relevant code from GameLogic.summon(..)

```
		context.getSummonStack().push(minion);

		log("{} summons {}", player.getName(), minion);
		minion.setOwner(player.getId());

		if (index < 0 || index >= player.getMinions().size()) {
			player.getMinions().add(minion);
		} else {
			player.getMinions().add(index, minion);
		}

		if (resolveBattlecry && minion.getBattlecry() != null && !minion.getBattlecry().isResolvedLate()) {
			resolveBattlecry(player.getId(), minion);
		}
```

So first, the new minion gets put to the SummonStack. In your planned version, this would be a list inside the Player class. But then the same minion is also added to the 'minions' list inside the Player, which means same minion is now a member of two different lists. This again creates a problem with cloning, because we cannot just clone both the 'minions' and new 'setAside' list, as this would lead to duplicate minions. Also as you already mentioned, the SummonStack is not the only problematic case, so we still would need a more general solution.

**Comment by webadict** [comment]
I realized that this is entirely unneeded because of the Battlecry update. Since the minion now fully exists within the Player's minion List, we no longer have to worry about resolving its Reference. We can now find the minion by adding the Reference to a SummonReferenceStack, so we know which minion is currently being summoned. I think I've got everything from there figured out, but Transformations still need to be rewritten because of this.

**Comment by webadict** [comment]
Well, geez, the whole Environment is basically a heap-load of Entities, isn't it? Seems like the cheater way is to change the Environment to hold references, which I've done with the Summon Stack and Transformation minions at the moment. It doesn't appear to cause any issues that I can tell, but I'll do some triple checking.

However, does the same hold true for Events? Should Events be holding EntityReferences instead of the Entities themselves as well?

**Comment by demilich1** [comment]
Changing the environment to hold only EntityReference instead of Entities is a good solution for now in my opinion. It would certainly make the game state easily clonable. And yes, basically the environment is just used to store Entities.

Events are fine though. They don't need to changed as they are volatile, meaning they are not stored anywhere. Basically you fire an event, it is processed and then it is gone. This causes no issues, as cloning only happens by the AI to prompt for an action.

One could argue that events should use also EntityReferences just for cleanness purposes and I would probably somewhat agree, but I think there are more important issues to be solved and as this one causes no troubles, I would leave it for now.

**Comment by webadict** [comment]
Alright, then I'll delay that until later. For now, I'll just get the Environment to be all EntityReferences.

**Comment by webadict** [comment]
I believe this is now fixed in the new PR. Sorry in advance for the number of changes.
