### ISSUE TITLE
Spiteful Smith not working correctly

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#79]
After the latest PR, the unit test for Spiteful Smith fails. I think the issue is that when the Spiteful Smith is already on the board and enraged and you equip a new weapon, it does not get buffed.

**Comment by webadict** [comment]
I'm not entirely sure what I changed to make this happen, but it does point at a rather larger issue. Auras themselves are kinda messed up. The easiest way to see this is with Faceless Manipulator, which allows a player to copy a minion with an Aura. Now, the easy fix is to not allow it to copy Aura bonuses, but this doesn't fix things like Wee Spellstopper's Auras from being copied.

I should make some test cases for Auras because there's probably a bunch of issues with them.

**Comment by webadict** [comment]
In fact, Wee Spellstopper has a couple of issues with it. Silencing, copying, multiple Spellstoppers, etc.

... Bleh. This is not going to be an easy fix. The only thing I can think of is having auras remove themselves and then re-apply themselves at certain points. Auras are one of the last things to apply themselves specifically for this, but Wee Spellstopper is another thing entirely (Might need to turn UNTARGETABLE_BY_SPELLS into an int value, like SPELL_DAMAGE.)

Any ideas? This one I might not be able to help out much on. Auras have always been hard to figure out.

**Comment by demilich1** [comment]
Yeah, auras are kind of hard to tame right now. Basically for them to work correctly, they have to use a dedicated stat, that's why AURA_ATTACK_BONUS exist. So, a quick fix would be to introduce AURA_UNTARGETABLE_BY_SPELLS and then add a method to Entity .isTargetableBySpells() which checks both attributes. It is not nice though and whenever a new card is introduced which applies some attribute via aura, we have to extend the code.

I was thinking of an alternative buff system recently, not just for auras, but for all buffs. At the moment, each Entity has a table of attributes and whenever a buff is applied, those attributes are changed. What if we just keep the base attributes in the table and buffs are added to some sort of list. And whenever an attribute value is requested, it takes the base value and applies all buffs by traversing through the buff list, outputting the final value at the end.

In my opinion there are several benefits to this 'node-based' approach, the most important one is that buffs are no longer destructive modifications of the original values. You would be able to remove just a single buff this way and the values would always be correct. Also we could add a name to each buff, to replicate the original Hearthstone UI, where you can hover over a minion and see which buffs are active. The only disadvantage I can think of, is that is will be a bit slower than the current solution, but I don't expect it to be a large performance hog.

I might try a prototype of that system in a branch; however I expect the final implementation to take quite some time (lot of refactoring involved), so maybe we should release 1.0.0 just as-it-is and keep the new buff system for 1.1.0? What do you think?

**Comment by webadict** [comment]
I like it. That feels more along the lines of Hearthstone.

Alright, how about we hack together something that covers up these minor
issues (I can patch Wee Spellstopper and Faceless, but I will never
understand Spiteful Smith) and then work towards that bigger change in
1.1.0? That gets 1.0.0 out there and ready to roll.

**Comment by demilich1** [comment]
Alright, I will take a look at Spiteful Smith later today.

**Comment by demilich1** [comment]
This is fixed now. The bug was actually related to BuffWeaponSpell and not to the aura itself. Also your recent changes had nothing to do with it, the spell was implemented inconsistently by me.
