### ISSUE TITLE
I made Starcraft 2 cards!

### ISSUE THREAD

**Issue by Chibi1234** [demilich1/metastone#8]
https://mega.nz/#F!mZ83XKoL!rwrngR4aXlvShYjehc1SkQ 
I made alot of custom cards using the new version and i just tought id let ya know that. Its around 60~ cards but some of them need some fixing. I was planning on making all zerg related cards beast but when i try to add ''RACE'':''BEAST'' and launch metastone it says error stuff. I was also wondering what program you use when editing the card files bc i use notepad and need something else bc notepad cx ._.

If you need some help im also willing to help! (Even tho im pretty limited by my brain in what i can do)

PS: The Zergling and Sentry cards arent working. (Sentry is based off Hogger and Zergling is Tidehunter) The sentry wont spawn the token_force_custom and the zergling wont spawn the token_zergling_custom (I name all the cards custom in the end bc idunno)

PSS: I copied all the Jarraxxus cards and renamed him arthas and made everything arthas-y like but when i played him i only got his weapon and the health. Not the hero power.

**Comment by demilich1** [comment]
That's great!

I spotted two minor errors in your files which explain why Zergling and Sentry are not working.

1. the token_zergling_custom.json has the entry "race" : "beast". At the moment MetaStone is very intolerant regarding basically everything, and it expects all races being written in uppercase. So change it to "race" : "BEAST" and it should work (this should also work for all other zerg cards you want to make BEAST)

2. The Sentry card itself looks fine, however the token it spawns has a wrong id (it is still called 'token_gnoll'). Changing this to 'token_force_custom' should fix this card.

I don't know what is the deal with your Arthas hero, but maybe it is also related to some case-sensitive shenanigans.

**Comment by Chibi1234** [comment]
O-O never thought you would respond so fast. Thanks for the info about zergling and the sentry. I'm going to try these solutions once I come home from new York in 4-5 days (We came here 5 minutes ago).

Also windfury harpie doesn't have an in game description. I noticed it when I made the Aiur Zealot. BTW do you think you can send me an example of a neutral 1/1 card with your hero is immune? I was trying to make a card with makes your hero immune but mal'ganis was a little bit hard to mod BC when I removed the aura effect the game crashes on launch. I tried a couple times adding the immune thing to other cards but I I think I'm doing it wrong. BTW what program are you using when editing the json files? Notepad I've realized is a mess. It has all the stuff like this for ex. Blablabla       (Blablabla)

And not

Blablabla
      Blablabla

(basically what I'm telling you is that notepad doesn't have sideways branches)

**Comment by Chibi1234** [comment]
I was trying to edit my comment but I'm new to github and I'm using phone at this will do. 

Add me on skip (If you got it.) I want to be able to help as much as I can with my 12 year old brain on metastone. Don't Think of me differently BC I'm 12 tho. I can do daily bug report or create tgt cards (To a basic extent) I think metastone is a great game... Simulator... Thingy. (Is it a game or a simulator? Idunno) maybe I'm asking to much of you and if your Skype mega private that's fine but I just want to help!

Skype: goderpachu

**Comment by demilich1** [comment]
I am using Notepad++ for editing the .json files. It is basically like the default Windows Notepad but on steroids. It is free, fast and powerful, can only recommend it. You can download it here: https://notepad-plus-plus.org/

**Comment by Chibi1234** [comment]
Okay thanks a lot! Imma download it when I get home from 🇺🇸 USA which I'm doing today! By the way demilich will boss cards be added? The ones that bosses from the adventures got? I'm just wondering. HOGGER SMASH! Lerl I'm so funneh. Kinda. Oh and also prepare your something bc a lot of new Issues will pop up once people want to make their own cards. If so I'm willing to halp the needy! (Well at least when I'm home BC MEGA won't allow me to see the text files thingy on phone

⊙ω⊙ hugs and maybe not kisses from chibi

**Comment by mayuso** [comment]
This job is really amazing, but can we please close this kind of "Issues"? Im not saying we shouldn´t open them, just close them when you have finished talking about it, because there is no real issue here.
Of course this is not my project and i don´t get to decide this kind of things, im just giving my opinion.

**Comment by Chibi1234** [comment]
Okay! *Closes issue*
