### ISSUE TITLE
Adding some tgt warrior cards

### ISSUE THREAD

**Issue by adozaraz** [demilich1/metastone#9]
https://mega.nz/#fm/gVpByJhY.
I made a some TGT Warrior card.
PS. King's defender battlecry didn't working(when you try to equip a weapon, game is crashing).
PSS. Alexstrasza's champion also didn't working(when you try to summon this minion, game is crashing).

**Comment by Chibi1234** [comment]
Its probably some case sensitive poop like always with metastone :P and ehmagers we can officially call us the 2 first metastone card makers (besides thy mighty Demolish!... Ehmagerd auto correct stahp! I meant demilich ) ⊙ω⊙

**Comment by demilich1** [comment]
Thanks adozaraz, unfortunately I could not access your folder, so I don't know exactly what the problem with the crashes was. But Chibi's guess sounds pretty sensible, maybe you just typed something in lower-case letters which was meant to be all upper-case. Anyway, I implemented all warrior cards myself, so this is no longer a concern. Still, thank you for your efforts!
