### ISSUE TITLE
[Gorehowl]Text not triggering

### ISSUE THREAD

**Issue by kairos4242** [demilich1/metastone#93]
Whenever Gorehowl is used to attack, it is destroyed immediately after instead of losing 1 attack. When I created a version of Gorehowl with two durability, to test if the text was merely triggering after the weapon was destroyed, the card text _still_ did not trigger, and the weapon still lost durability. I'm not sure why this could be, as the report log does not give any indication that something has gone wrong. Perhaps some sort of formatting error?

**Comment by webadict** [comment]
Ah, that's probably because TargetAcquisitionEvent is being weird. I think I know the issue.

**Comment by webadict** [comment]
Yeah, tested it now, it should be working correctly in the next PR.

**Comment by webadict** [comment]
Fixed with #92.
