### ISSUE TITLE
[Bug]Odd bug using DiscardSpell and DrawCardSpell

### ISSUE THREAD

**Issue by kairos4242** [demilich1/metastone#99]
This bug occurs in both play mode and sandbox mode. I haven't tried it out in simulation mode due to time constraints, but I will as soon as possible.

Here's the card that the bug occurs with:
![capture2](https://cloud.githubusercontent.com/assets/17713263/13733919/2e664100-e95e-11e5-9aae-54d9f057bbb9.PNG)

As soon as it is possible to play the card, meaning it is in your hand and you have at least four mana, all icons in the actions menu disappear, leaving you unable to do anything but close Metastone.
![capture](https://cloud.githubusercontent.com/assets/17713263/13733879/d08ac628-e95d-11e5-83e1-003d85628280.PNG)

I've checked both the .log and my code, and neither seems to offer any insight into what the problem is. Is this a bug or just poor coding on my part?

**Comment by webadict** [comment]
MetaSpell now uses the "spells" keyword. It's an array of spells, so it should look like
"spells": [
{
"class": "DiscardSpell"
},
{
"class": "DrawSpell"
}
]

instead of "spell1" and "spell2"

**Comment by kairos4242** [comment]
Alright, thank you so much!

**Comment by webadict** [comment]
If that fixes it, let me know. Otherwise, I'll try to see what's up.

**Comment by kairos4242** [comment]
Okay, changed MetaSpell to an array, but the bug is still happening. Still looks the same as before too, with no available actions.
![capture5](https://cloud.githubusercontent.com/assets/17713263/13764350/088e7d56-ea14-11e5-9c8a-59bd80147376.PNG)

I've tried playing with all the variables, who discards cards, who draws them, the amount of cards drawn and discarded, but nothing appears to be working or even showing different symptoms. I can't replicate it using any other combination of spells with MetaSpell either, but I've only tried a handful.

**Comment by webadict** [comment]
Your forgot TargetSelection. Add this line to the card:
"targetSelection": "NONE"

**Comment by kairos4242** [comment]
Ah man, cannot believe I forgot about that. Thanks so much for the quick replies, and so sorry to be delaying your work with basic questions. I'll try and only report real bugs from now on.

**Comment by webadict** [comment]
Don't worry about it. You're not taking up any time I was planning to use
productively anyhow.
